export const COMBAT_VFX_DETAIL_TEXT = Object.freeze({
  title: "Combat VFX Placement Preview",
  description: "Read-only placement summary for player and monster attack effects.",
  summary: "Players {playerRows} / Monsters {monsterRows} / Effects {effectTypes}",
  playerTitle: "Player Attack Effects",
  monsterTitle: "Monster Attack Effects",
  base: "Base",
  hyper: "Hyper",
  effects: "Effect Types",
  motion: "Motion",
  sfx: "SFX",
  placement: "Placement",
  sprite: "Sprite",
  playerMetric: "Player VFX",
  monsterMetric: "Monster VFX",
  profileMetric: "Motion Profiles",
  profileTuningMetric: "Profile Signals",
  effectMetric: "Effect Types",
  tuningMetric: "Tuning Signals",
  tuningTitle: "Tuning Signal Summary",
  tuningDescription: "Review wide or offset-heavy placements first before manual VFX tuning.",
  profileTitle: "Monster Motion Profile Summary",
  profileDescription: "Compare monster VFX ranges by runtime motion profile before editing placement values.",
  profileCount: "{count} profiles",
  profileMonsterCount: "{count} monsters",
  profileBaseRange: "Base range",
  profileHyperRange: "Hyper range",
  profileDefaultEffects: "Default effects",
  profileModifiers: "Profile modifiers",
  profileEffects: "Effect ranges",
  profileSignals: "Profile signals",
  noProfileSignals: "Stable range",
  candidateCount: "{count} candidates",
  candidatePriority: "Priority {priority}",
  candidateSignals: "Signals",
  candidatePlacement: "Placement",
  noTuningCandidates: "No tuning signals",
  metricLabel: "Combat VFX",
  metricValue: "Players {playerRows} ? Monsters {monsterRows}",
  metricHint: "Attack effect placement preview ready",
  classLabels: {},
  genderLabels: {},
  effectLabels: {},
  signalLabels: {},
});

export const COMBAT_VFX_CLASS_LABELS = Object.freeze({
  warrior: "Warrior",
  assassin: "Assassin",
  fighter: "Fighter",
  archer: "Archer",
  mage_wandbook: "Wand-book Mage",
  mage_staff: "Staff Mage",
});

export const COMBAT_VFX_GENDER_LABELS = Object.freeze({
  male: "Male",
  female: "Female",
});

export const COMBAT_VFX_EFFECT_LABELS = Object.freeze({
  slash: "Slash",
  impact: "Impact",
  pierce: "Pierce",
  projectile: "Projectile",
  magic: "Magic",
  holy: "Holy",
  dark: "Dark",
  explosion: "Explosion",
});

export const COMBAT_VFX_SIGNAL_LABELS = Object.freeze({
  "expanded-width-critical": "Expanded slash critical",
  "expanded-width-wide": "Expanded slash wide",
  "slash-width-wide": "Slash width wide",
  "vertical-offset-high": "Vertical offset high",
  "horizontal-offset-high": "Horizontal offset high",
  "text-offset-high": "Text offset high",
});
