export const MONSTER_SPRITE_REPORT_TEXT = Object.freeze({
  title: "Monster Battle Sprite Slot Readiness",
  description: "Read-only checklist for monster idle, attack, hit, and dead sprite files before final PNG/WebP production.",
  slotMetric: "Total Slots",
  assignedMetric: "Assigned",
  connectableMetric: "Connectable",
  missingMetric: "Missing",
  brokenMetric: "Broken",
  fileScanMetric: "File-ready",
  fallbackMetric: "CSS fallback",
  connectionPlanTitle: "Ready Connection Plan",
  connectionPlanDescription: "Only file-ready monster sprites become connection patch candidates.",
  readyPatchMetric: "Ready patches",
  readyManifestMetric: "Manifest entries",
  readyFileMetric: "Ready files",
  missingFileMetric: "Missing files",
  applyModeMetric: "Apply mode",
  reviewStatusMetric: "Review status",
  reviewChecklistTitle: "Review gate",
  reviewCheckPassed: "OK",
  reviewCheckPending: "Pending",
  handoffTitle: "Missing File Handoff",
  handoffDescription: "Output-only production handoff for the exact monster WebP files that are still missing.",
  handoffArtifactMetric: "Artifact",
  handoffScriptMetric: "Script",
  handoffMissingMetric: "Missing files",
  handoffGroupsMetric: "Monster groups",
  nextStepLabels: {
    "add-monster-files": "Add the expected WebP files before applying sprite slot patches.",
    "review-ready-patch": "Review art, manifest entries, and slot patches before applying.",
    "fix-broken-slots": "Fix broken assigned sprite slots before adding new ready patches.",
  },
  reviewCheckLabels: {
    "file-ready-only": "Only file-ready rows can become patches",
    "has-ready-files": "At least one monster sprite file is ready",
    "no-broken-slots": "No broken assigned monster sprite slots",
    "ready-patches-match-connectable": "Ready patch count matches connectable rows",
  },
  expectedPath: "Expected file",
  assignedAsset: "Assigned asset",
  suggestedAsset: "Suggested asset",
  slotPatch: "Slot patch",
  fileStatus: "File scan",
  runtimePath: "Runtime path",
  runtimePreview: "Runtime preview",
  fallbackMode: "Fallback",
  fallbackSummaryTitle: "Fallback summary",
  fallbackSummaryDescription: "Runtime fallback distribution before final monster art is assigned.",
  monsterFallbackSummary: "Monster fallback states",
  defaultSlot: "Default slot",
  fallbackModeLabels: {
    "assigned-asset": "Assigned asset",
    "broken-asset": "Broken asset",
    "default-slot": "Default slot",
    "css-placeholder": "CSS placeholder",
  },
  statusLabels: {
    assigned: "Assigned",
    connectable: "Connectable",
    missing: "Missing",
    broken: "Broken",
  },
  fileStatusLabels: {
    "not-scanned": "Not scanned",
    "file-ready": "File ready",
    "file-missing": "File missing",
  },
});
