export const BALANCE_TUNING_REQUIRED_GROUP_IDS = [
  "player-stats",
  "player-growth",
  "combat-damage",
  "combat-rank-hyper",
  "equipment-values",
  "items",
  "monsters",
  "monster-stats",
  "skills",
  "rewards",
  "recovery",
];

export const BALANCE_TUNING_GROUPS = [
  {
    id: "player-stats",
    scope: "engine-balance",
    files: ["src/balance/playerStatBalance.js"],
    exports: ["PLAYER_GEAR_BALANCE", "PLAYER_STAT_FORMULA", "PLAYER_POWER_WEIGHTS"],
    affects: ["player-derived-stats", "combat-power", "drop-rate"],
  },
  {
    id: "player-growth",
    scope: "engine-balance",
    files: ["src/balance/playerGrowthBalance.js"],
    exports: ["LEVEL_UP_FREE_POINTS", "PLAYER_BASE_STAT_VALUE", "INITIAL_CREATION_STAT_BALANCE", "BULK_STAT_DEALLOCATE_AMOUNT"],
    affects: ["level-up", "stat-allocation", "character-creation"],
  },
  {
    id: "combat-damage",
    scope: "engine-balance",
    files: ["src/balance/damageBalance.js"],
    exports: ["PLAYER_DAMAGE_BALANCE", "ENEMY_DAMAGE_BALANCE"],
    affects: ["player-damage", "enemy-damage", "accuracy", "critical-hit"],
  },
  {
    id: "combat-rank-hyper",
    scope: "engine-balance",
    files: ["src/balance/combatBalance.js"],
    exports: [
      "PLAYER_HYPER_BASE_DURATION_SECONDS",
      "PLAYER_HYPER_BASE_COOLDOWN_SECONDS",
      "ENEMY_HYPER_BASE_DURATION_SECONDS",
      "ENEMY_HYPER_BASE_COOLDOWN_SECONDS",
      "HYPER_CHARGE_BALANCE",
      "HYPER_SCALING_BALANCE",
      "BREAK_GAUGE_BALANCE",
      "COMBAT_RUNTIME_BALANCE",
      "RANK_ORDER",
      "RANK_POWER_THRESHOLDS",
    ],
    affects: ["rank-gap", "hyper", "break-gauge", "combat-runtime"],
  },
  {
    id: "equipment-values",
    scope: "engine-balance",
    files: ["src/balance/equipmentValueBalance.js"],
    exports: ["SHOP_PRICE_BALANCE", "EQUIPMENT_SCORE_BALANCE"],
    affects: ["shop-price", "recommended-equipment", "equipment-score"],
  },
  {
    id: "items",
    scope: "content-balance",
    files: ["src/balance/itemBalanceData.js"],
    exports: ["ITEM_BALANCE_DATA"],
    affects: ["equipment-stats", "equipment-options", "item-pool"],
  },
  {
    id: "monsters",
    scope: "content-balance",
    files: ["src/balance/monsterBalanceData.js"],
    exports: ["MONSTER_BALANCE_DATA"],
    affects: ["monster-levels", "monster-stats", "exp", "gold", "drop-table"],
  },
  {
    id: "monster-stats",
    scope: "engine-balance",
    files: ["src/balance/monsterStatBalance.js"],
    exports: ["MONSTER_STAT_FORMULA", "MONSTER_POWER_WEIGHTS"],
    affects: ["monster-derived-stats", "monster-power"],
  },
  {
    id: "skills",
    scope: "content-balance",
    files: ["src/balance/skillBalanceData.js"],
    exports: ["SKILL_BALANCE_DATA"],
    affects: ["active-skills", "damage-multiplier", "healing", "mp-cost"],
  },
  {
    id: "rewards",
    scope: "engine-balance",
    files: ["src/balance/rewardBalance.js"],
    exports: ["LEVEL_UP_AUTO_STATS", "REWARD_MULTIPLIER_MIN", "REWARD_MULTIPLIER_MAX", "REGION_EXP_MULTIPLIER_BY_OVERLEVEL", "OFFLINE_REWARD_BALANCE"],
    affects: ["level-up-auto-stats", "exp-scaling", "gold-scaling", "offline-reward"],
  },
  {
    id: "recovery",
    scope: "engine-balance",
    files: ["src/balance/recoveryBalance.js"],
    exports: ["PASSIVE_RECOVERY_BALANCE", "DEFEAT_RECOVERY_BALANCE"],
    affects: ["passive-recovery", "defeat-recovery"],
  },
];
