export const ITEM_BALANCE_DATA = [
  { id: "rusty_sword", slot: "Weapon", rarity: "common", attack: 1, defaultEffectType: "slash", options: [{ type: "STR", value: 1 }] },
  { id: "hunter_bow", slot: "Weapon", rarity: "uncommon", attack: 2, defaultEffectType: "projectile", options: [{ type: "AGI", value: 2 }] },
  { id: "golem_fist", slot: "Weapon", rarity: "rare", attack: 4, defaultEffectType: "impact", options: [{ type: "VIT", value: 2 }] },
  { id: "rift_blade", slot: "Weapon", rarity: "heroic", attack: 7, defaultEffectType: "slash", options: [{ type: "STR", value: 3 }, { type: "LUK", value: 1 }] },
  { id: "worn_gloves", slot: "Gloves", rarity: "common", defense: 1, options: [{ type: "AGI", value: 1 }] },
  { id: "wolf_leather_armor", slot: "Armor", rarity: "uncommon", defense: 2, options: [{ type: "VIT", value: 2 }] },
  { id: "swift_boots", slot: "Boots", rarity: "uncommon", defense: 1, options: [{ type: "AGI", value: 2 }] },
  { id: "sentinel_helmet", slot: "Helmet", rarity: "rare", defense: 1, options: [{ type: "WIS", value: 2 }] },
  { id: "tower_shield_armor", slot: "Armor", rarity: "rare", defense: 4, options: [{ type: "VIT", value: 3 }] },
  { id: "mana_necklace", slot: "Necklace", rarity: "rare", defense: 1, options: [{ type: "INT", value: 2 }, { type: "WIS", value: 2 }] },
  { id: "ore_plate", slot: "Armor", rarity: "heroic", defense: 6, options: [{ type: "VIT", value: 4 }] },
  { id: "lucky_ring", slot: "Ring", rarity: "rare", defense: 0, options: [{ type: "LUK", value: 3 }] },
  { id: "shore_ring", slot: "Ring", rarity: "common", defense: 0, options: [{ type: "WIS", value: 1 }] },
  { id: "rift_gauntlets", slot: "Gloves", rarity: "heroic", defense: 2, options: [{ type: "STR", value: 2 }, { type: "AGI", value: 2 }] },
  { id: "regressor_charm", slot: "Necklace", rarity: "legendary", defense: 2, options: [{ type: "LUK", value: 4 }, { type: "WIS", value: 3 }] },
  { id: "warden_crown", slot: "Helmet", rarity: "legendary", defense: 5, options: [{ type: "INT", value: 4 }, { type: "WIS", value: 4 }] },
  { id: "perfect_timeline_ring", slot: "Ring", rarity: "legendary", defense: 1, options: [{ type: "STR", value: 3 }, { type: "AGI", value: 3 }, { type: "LUK", value: 3 }] },
  { id: "ash_boots", slot: "Boots", rarity: "rare", defense: 2, options: [{ type: "AGI", value: 3 }] },
  { id: "iron_gloves", slot: "Gloves", rarity: "common", defense: 1, options: [{ type: "STR", value: 1 }] },
  { id: "novice_helmet", slot: "Helmet", rarity: "common", defense: 1, options: [{ type: "VIT", value: 1 }] },
];

export const LOOT_ITEM_BALANCE_DATA = [
  { id: "imp_codex_fragment", type: "codex_fragment", rarity: "common", stackable: true, recordTarget: 5 },
  { id: "shore_claw_crab_codex_fragment", type: "codex_fragment", rarity: "common", stackable: true, recordTarget: 5 },
  { id: "shore_drift_slime_codex_fragment", type: "codex_fragment", rarity: "common", stackable: true, recordTarget: 5 },
  { id: "forest_wolf_codex_fragment", type: "codex_fragment", rarity: "common", stackable: true, recordTarget: 5 },
  { id: "forest_goblin_scout_codex_fragment", type: "codex_fragment", rarity: "uncommon", stackable: true, recordTarget: 5 },
  { id: "forest_alpha_wolf_codex_fragment", type: "codex_fragment", rarity: "uncommon", stackable: true, recordTarget: 5 },
  { id: "ruin_sentinel_codex_fragment", type: "codex_fragment", rarity: "uncommon", stackable: true, recordTarget: 5 },
  { id: "ruin_rune_doll_codex_fragment", type: "codex_fragment", rarity: "uncommon", stackable: true, recordTarget: 5 },
  { id: "mine_crystal_bug_codex_fragment", type: "codex_fragment", rarity: "uncommon", stackable: true, recordTarget: 5 },
  { id: "mine_golem_codex_fragment", type: "codex_fragment", rarity: "uncommon", stackable: true, recordTarget: 5 },
  { id: "mine_core_golem_codex_fragment", type: "codex_fragment", rarity: "rare", stackable: true, recordTarget: 5 },
  { id: "rift_squire_codex_fragment", type: "codex_fragment", rarity: "rare", stackable: true, recordTarget: 5 },
  { id: "rift_shieldbearer_codex_fragment", type: "codex_fragment", rarity: "rare", stackable: true, recordTarget: 5 },
  { id: "rift_knight_codex_fragment", type: "codex_fragment", rarity: "rare", stackable: true, recordTarget: 5 },
  { id: "rift_warden_codex_fragment", type: "codex_fragment", rarity: "heroic", stackable: true, recordTarget: 5 },
  { id: "low_mana_crystal_fragment", type: "mana_crystal", rarity: "common", stackable: true },
  { id: "unstable_mana_crystal_fragment", type: "mana_crystal", rarity: "uncommon", stackable: true },
  { id: "mine_core_mana_crystal_fragment", type: "mana_crystal", rarity: "rare", stackable: true },
  { id: "rift_mana_crystal_fragment", type: "mana_crystal", rarity: "rare", stackable: true },
  { id: "power_slash_skill_fragment", type: "skill_fragment", rarity: "common", stackable: true, skillId: "power_slash" },
  { id: "quick_step_skill_fragment", type: "skill_fragment", rarity: "uncommon", stackable: true, skillId: "quick_step" },
  { id: "guard_stance_skill_rune", type: "skill_rune", rarity: "rare", stackable: true, skillId: "guard_stance" },
  { id: "mana_bolt_skill_rune", type: "skill_rune", rarity: "rare", stackable: true, skillId: "mana_bolt" },
  { id: "mana_ignite_skill_rune", type: "skill_rune", rarity: "rare", stackable: true, skillId: "mana_ignite" },
];
