export const MONSTER_BALANCE_DATA = [
  {
    id: "shore_imp",
    regionId: "tutorial_shore",
    level: 1,
    stats: { STR: 1, AGI: 2, VIT: 2, INT: 0, WIS: 0, LUK: 0 },
    exp: 16,
    gold: 3,
    dropTable: [
      { itemId: "rusty_sword", chance: 0.07 },
      { itemId: "worn_gloves", chance: 0.06 },
      { itemId: "shore_ring", chance: 0.025 },
      { itemId: "imp_codex_fragment", chance: 0.12 },
      { itemId: "low_mana_crystal_fragment", chance: 0.06 },
    ],
  },
  {
    id: "forest_wolf",
    regionId: "tutorial_forest",
    level: 2,
    stats: { STR: 4, AGI: 6, VIT: 4, INT: 0, WIS: 1, LUK: 1 },
    exp: 45,
    gold: 7,
    dropTable: [
      { itemId: "wolf_leather_armor", chance: 0.065 },
      { itemId: "swift_boots", chance: 0.045 },
      { itemId: "hunter_bow", chance: 0.04 },
      { itemId: "forest_wolf_codex_fragment", chance: 0.09 },
      { itemId: "quick_step_skill_fragment", chance: 0.035 },
    ],
  },
  {
    id: "ruin_sentinel",
    regionId: "broken_ruins",
    level: 4,
    stats: { STR: 8, AGI: 3, VIT: 11, INT: 1, WIS: 3, LUK: 1 },
    exp: 90,
    gold: 14,
    dropTable: [
      { itemId: "sentinel_helmet", chance: 0.06 },
      { itemId: "tower_shield_armor", chance: 0.035 },
      { itemId: "mana_necklace", chance: 0.03 },
      { itemId: "ruin_sentinel_codex_fragment", chance: 0.085 },
      { itemId: "guard_stance_skill_rune", chance: 0.025 },
    ],
  },
  {
    id: "mine_golem",
    regionId: "mana_mine",
    level: 6,
    stats: { STR: 11, AGI: 3, VIT: 18, INT: 2, WIS: 5, LUK: 1 },
    exp: 160,
    gold: 26,
    dropTable: [
      { itemId: "golem_fist", chance: 0.05 },
      { itemId: "ore_plate", chance: 0.045 },
      { itemId: "lucky_ring", chance: 0.025 },
      { itemId: "mine_golem_codex_fragment", chance: 0.08 },
      { itemId: "low_mana_crystal_fragment", chance: 0.12 },
      { itemId: "unstable_mana_crystal_fragment", chance: 0.04 },
    ],
  },
  {
    id: "rift_knight",
    regionId: "rift_gate",
    level: 9,
    stats: { STR: 22, AGI: 12, VIT: 27, INT: 5, WIS: 10, LUK: 3 },
    exp: 260,
    gold: 46,
    dropTable: [
      { itemId: "rift_blade", chance: 0.04 },
      { itemId: "rift_gauntlets", chance: 0.04 },
      { itemId: "regressor_charm", chance: 0.02 },
      { itemId: "rift_knight_codex_fragment", chance: 0.07 },
      { itemId: "rift_mana_crystal_fragment", chance: 0.045 },
    ],
  },
  {
    id: "rift_warden",
    regionId: "rift_gate",
    level: 10,
    isBoss: true,
    stats: { STR: 28, AGI: 14, VIT: 44, INT: 8, WIS: 14, LUK: 4 },
    exp: 620,
    gold: 125,
    dropTable: [
      { itemId: "warden_crown", chance: 0.175 },
      { itemId: "perfect_timeline_ring", chance: 0.06 },
      { itemId: "rift_blade", chance: 0.1 },
      { itemId: "rift_warden_codex_fragment", chance: 0.16 },
      { itemId: "mana_ignite_skill_rune", chance: 0.07 },
      { itemId: "rift_mana_crystal_fragment", chance: 0.12 },
    ],
  },
];
