export const SKILL_BALANCE_DATA = [
  {
    id: "power_slash",
    type: "Active",
    mpCost: 2,
    cooldown: 4,
    damageType: "physical",
    element: "physical",
    multiplier: 1.35,
    effectType: "slash",
    breakPower: 1,
    stanceAllowed: ["power", "berserk"],
    triggerCondition: "always",
  },
  {
    id: "mana_bolt",
    type: "Active",
    mpCost: 3,
    cooldown: 5,
    damageType: "magic",
    element: "neutral",
    multiplier: 1.45,
    effectType: "magic",
    breakPower: 1,
    stanceAllowed: ["power", "berserk"],
    triggerCondition: "always",
  },
  {
    id: "emergency_recovery",
    type: "Active",
    mpCost: 4,
    cooldown: 12,
    damageType: "support",
    element: "light",
    multiplier: 0,
    effectType: "holy",
    breakPower: 0,
    triggerHpRatio: 0.3,
    heal: {
      maxHpRatio: 0.35,
      wisScale: 0.25,
    },
    stanceAllowed: ["conserve", "power", "berserk", "break_wait"],
    triggerCondition: "playerHpBelow30",
  },
];
