export const SKILL_BALANCE_DATA = [
  {
    id: "power_slash",
    actionAlias: "heavy_strike",
    type: "Active",
    mpCost: 0,
    cooldown: 1,
    damageType: "physical",
    element: "physical",
    multiplier: 1.6,
    accuracyModifier: -0.05,
    effectType: "impact",
    breakPower: 1,
    stanceAllowed: ["power", "berserk"],
    triggerCondition: "always",
  },
  {
    id: "mana_bolt",
    actionAlias: "magic_bolt",
    type: "Active",
    mpCost: 24,
    cooldown: 0,
    damageType: "magic",
    element: "neutral",
    multiplier: 1.25,
    effectType: "magic",
    breakPower: 1,
    stanceAllowed: ["power", "berserk"],
    triggerCondition: "always",
  },
  {
    id: "quick_step",
    type: "Active",
    mpCost: 1,
    cooldown: 3,
    damageType: "physical",
    element: "physical",
    multiplier: 1.15,
    effectType: "slash",
    breakPower: 0.5,
    stanceAllowed: ["power", "berserk"],
    triggerCondition: "always",
  },
  {
    id: "guard_stance",
    type: "Active",
    mpCost: 2,
    cooldown: 10,
    damageType: "support",
    element: "physical",
    multiplier: 0,
    effectType: "holy",
    breakPower: 0,
    triggerHpRatio: 0.45,
    heal: {
      maxHpRatio: 0.18,
      wisScale: 0.15,
    },
    stanceAllowed: ["conserve", "power", "berserk", "break_wait"],
    triggerCondition: "playerHpBelow45",
  },
  {
    id: "mana_ignite",
    type: "Active",
    mpCost: 2,
    cooldown: 4,
    damageType: "magic",
    element: "neutral",
    multiplier: 1.22,
    effectType: "magic",
    breakPower: 0.75,
    stanceAllowed: ["power", "berserk"],
    triggerCondition: "always",
  },
  {
    id: "emergency_recovery",
    actionAlias: "emergency_heal",
    type: "Active",
    mpCost: 35,
    cooldown: 3,
    damageType: "support",
    element: "light",
    multiplier: 0,
    effectType: "holy",
    breakPower: 0,
    manualAlwaysAvailable: true,
    triggerHpRatio: 0.3,
    heal: {
      maxHpRatio: 0.28,
      wisScale: 0.25,
    },
    stanceAllowed: ["conserve", "power", "berserk", "break_wait"],
    triggerCondition: "playerHpBelow30",
  },
  {
    id: "preserve",
    type: "Active",
    mpCost: 20,
    cooldown: 3,
    damageType: "buff",
    element: "light",
    multiplier: 0,
    effectType: "holy",
    breakPower: 0,
    buff: {
      id: "preserve_guard",
      duration: 1,
      incomingDamageMultiplier: 0.5,
      consumeOnHit: true,
    },
    stanceAllowed: ["conserve", "power", "berserk", "break_wait"],
    triggerCondition: "always",
  },
  {
    id: "full_power",
    type: "Active",
    mpCost: 30,
    cooldown: 4,
    damageType: "buff",
    element: "physical",
    multiplier: 0,
    effectType: "impact",
    breakPower: 0,
    buff: {
      id: "full_power",
      duration: 2,
      outgoingDamageMultiplier: 1.25,
    },
    stanceAllowed: ["conserve", "power", "berserk", "break_wait"],
    triggerCondition: "always",
  },
  {
    id: "rampage",
    type: "Active",
    mpCost: 0,
    cooldown: 5,
    damageType: "buff",
    element: "dark",
    multiplier: 0,
    effectType: "impact",
    breakPower: 0,
    selfHpCostRatio: 0.08,
    buff: {
      id: "rampage",
      duration: 3,
      outgoingDamageMultiplier: 1.45,
      incomingDamageMultiplier: 1.2,
    },
    stanceAllowed: ["conserve", "power", "berserk", "break_wait"],
    triggerCondition: "always",
  },
];
