export function createAppRenderContext({
  options = {},
  state,
  uiState,
  saveSlotEntries = [],
  activeSaveSlotId,
  combatRuntime,
  assetRegistry,
  regions,
  shopCatalog,
  shopCategories,
  slots,
  primaryStats,
  slowRenderIntervalMs,
  nextSlowRenderAt,
  hypMax,
  expToNext,
  ensureResources,
  derivePlayer,
  getRegion,
  resolveRegionMonster,
  getMonster,
  getMonsterStats,
  getItem,
  getGateMap,
  ensureGateProgress,
  getRegionMoveBlock,
  displayName,
  optionText,
  getCombatActionRenderContext,
  regressionCardCandidates,
  regressionCardDrawTestState,
  resolveRegionCardImagePath,
  resolveRegionNodeMapImagePath,
  resolveRegionBattleBackgroundPath,
  resolvePlayerCombatSpritePath,
  resolveMonsterCombatSpritePath,
  resolveItemIconPath,
  latestDialogueEventRecords = [],
  onToggleObjective,
  onToggleObjectiveRotationMode,
  onStepObjective,
  onObjectiveAction,
}) {
  return {
    options,
    state,
    uiState,
    saveSlotEntries,
    activeSaveSlotId,
    combatRuntime,
    assetRegistry,
    regions,
    shopCatalog,
    shopCategories,
    slots,
    primaryStats,
    slowRenderIntervalMs,
    nextSlowRenderAt,
    hypMax,
    expToNext,
    ensureResources,
    derivePlayer,
    getRegion,
    resolveRegionMonster,
    getMonster,
    getMonsterStats,
    getItem,
    getGateMap,
    ensureGateProgress,
    getRegionMoveBlock,
    displayName,
    optionText,
    getCombatActionRenderContext,
    regressionCardCandidates,
    regressionCardDrawTestState,
    resolveRegionCardImagePath,
    resolveRegionNodeMapImagePath,
    resolveRegionBattleBackgroundPath,
    resolvePlayerCombatSpritePath,
    resolveMonsterCombatSpritePath,
    resolveItemIconPath,
    latestDialogueEventRecords,
    onToggleObjective,
    onToggleObjectiveRotationMode,
    onStepObjective,
    onObjectiveAction,
  };
}

export function createCombatActionRenderContext({
  state,
  combatRuntime,
  helpText,
  hideHint,
  combatActionList,
  getCombatAction,
  skillAvailability,
  actionTriggerText,
}) {
  return {
    state,
    combatRuntime,
    helpText,
    hideHint,
    combatActionList,
    getCombatAction,
    skillLoadouts: () => state.skillLoadouts,
    activeSkillLoadoutId: () => state.activeSkillLoadoutId,
    skillAvailability,
    actionTriggerText,
  };
}
