import { t } from "../localization/index.js?v=370";

export function createInitialState({
  slots,
  regions,
  defaultCombatFeedback,
  defaultCombatView,
  defaultDeveloperOptions,
  defaultPlayerProfile,
  defaultSkillLoadouts,
  defaultActiveSkillLoadoutId,
}) {
  return {
    player: {
      name: t("saveSlots.fallbackName"),
      level: 1,
      exp: 0,
      gold: 0,
      freePoints: 0,
      pendingStatAllocations: {},
      stats: { STR: 5, AGI: 5, VIT: 5, INT: 5, WIS: 5, LUK: 5 },
      hp: 0,
      mp: null,
    },
    playerProfile: { ...defaultPlayerProfile },
    equipment: Object.fromEntries(slots.map((slot) => [slot, null])),
    inventory: [],
    regionId: regions[0].id,
    completedRegions: [],
    skillLoadouts: defaultSkillLoadouts.map((loadout) => ({ ...loadout, actionIds: [...loadout.actionIds] })),
    activeSkillLoadoutId: defaultActiveSkillLoadoutId,
    target: null,
    inCombat: false,
    resting: false,
    autoHunt: false,
    stance: "power",
    hitCount: 0,
    hyp: 0,
    hyperActiveTicks: 0,
    hyperDuration: 0,
    hyperCooldown: 0,
    lastHitAt: 0,
    effects: [],
    settings: {
      combatFeedback: { ...defaultCombatFeedback },
      combatView: { ...defaultCombatView },
      developer: { ...defaultDeveloperOptions },
    },
    gateProgress: {},
    log: [t("stateMessages.initialLog")],
    lastSeenAt: Date.now(),
    offlineAutoHuntEligible: false,
    offlineAutoHuntEngagedAt: 0,
  };
}
