export const KO_KR_TEXT = {
  common: {
    cancel: "취소",
    confirm: "확인",
    next: "다음",
    previous: "이전",
    systemInitialization: "SYSTEM INITIALIZATION",
  },
  contentProfile: {
    projectRegressorHunter: {
      title: "Project Regressor",
      description: "한국 판타지 헌터물 스타일 방치형 RPG",
    },
    koreanFantasyMurimTemplate: {
      title: "한국 판타지 무협 방치형 RPG",
      description: "한국 판타지 무협물 스타일 방치형 RPG 템플릿",
    },
  },
  retargetSamples: {
    murim: {
      profile: {
        title: "무림 회귀록",
        description: "한국 판타지 무협물 스타일 방치형 RPG",
        templateDescription: "문파와 강호를 오르는 무협 방치형 RPG 템플릿",
      },
      staticShell: {
        characterCreationTitle: "무인 등록",
        defaultName: "귀환자",
        questionRules: "강호의 법도와 문파의 규율에 대해 어떻게 생각하는가?",
        questionOrder: "소속 문파의 장문인이 부당한 명령을 내렸다.",
        submit: "운명 동기화",
        compactObjective: "5개 구역을 돌파하고 마교 관문의 수문장을 처치하세요.",
        systemWindowTitle: "무공 시스템",
        systemWindowMessage: "시스템이 귀환자의 기연 기록과 동기화 중입니다.",
        defaultRegionLore: "첫 기운의 틈이 열린 나루터. 약한 요물이 떠밀려온다.",
        nodeMapPanelTitle: "시련 노드맵",
        nodeMapEyebrow: "강호 시련",
        playerName: "귀환자",
        statusWindowTitle: "무인 상태창",
        defaultStatusWindow: "귀환자 상태창",
        portraitLabel: "무인 이미지",
      },
      characterCreation: {
        registrationName: "무인 등록명",
        defaultImage: "기본 무인 이미지",
        questionDescription: "당신의 성향을 파악하기 위해 시스템이 강호의 질문을 던집니다.",
        completionMessage: "무인 등록이 끝났습니다. 기운의 틈이 열린 초입으로 이동합니다.",
        start: "입문 시작",
      },
      runtimeUi: {
        initialLog: "시스템이 귀환자의 기연 기록과 동기화되었습니다. 첫 비무를 시작하세요.",
        idleMessage: "귀환자의 기연 기록을 동기화했습니다.",
        riftWeakened: "기운의 틈 약화",
        finalGateDetail: "마교 관문의 수문장을 쓰러뜨리면 초입 시련이 끝납니다.",
      },
      dataSkills: {
        qiBurstName: "기탄",
        qiBurstDescription: "응축한 내공을 적에게 쏘아 보낸다.",
      },
      dataEquipment: {
        wanderingArcherBow: "유랑 궁수의 활",
        demonicSaber: "마도 절혼도",
        sectGuardArmor: "문파 호위 갑주",
        qiFlowNecklace: "기맥 목걸이",
        ironQiGauntlets: "철기 장갑",
        returnerJadeTalisman: "귀환자의 옥패",
        heavenlyCycleRing: "천환 반지",
      },
      dataMonsters: {
        oreQiPuppet: "광맥 기갑목인",
        demonicCultSwordsman: "마교 검수",
        demonicCultWarden: "마교 관문 수문장",
      },
      dataRegions: {
        spiritStoneMineName: "영석 광산",
        spiritStoneMineDescription: "초입 성장을 가속하는 영석 광맥.",
        demonicSectGateName: "마교 관문",
        demonicSectGateDescription: "초입 시련의 마지막 관문. 수문장을 쓰러뜨리면 시련이 끝난다.",
      },
      dataGateMaps: {
        sectRuinsTrial: "폐문파 시련",
      },
      dataShops: {
        returnerCategoryName: "귀환자 기연품",
        returnerCategoryDescription: "반복되는 운명을 통해 가치를 알아보게 되는 고가의 장비입니다.",
        returnerJadeTalismanNote: "귀환자 전용 성장감을 확인하기 위한 고가 장비입니다.",
      },
    },
  },
  retargetPreview: {
    title: "테마 샘플 미리보기",
    summary: "{title} · 텍스트 {textCount} · 에셋 {assetCount}",
    profileRoute: "{source} → {target}",
    ready: "미리보기 준비 완료",
    needsReview: "검토 필요 · 텍스트 누락 {missingText} · 에셋 누락 {missingAssets} · 에셋 불일치 {mismatchedAssets}",
  },
  staticHtml: {
    characterCreation: {
      ariaLabel: "캐릭터 생성",
      title: "시스템 등록",
      description: "첫 세계선에 기록할 기본 정보를 입력합니다.",
      name: "이름",
      defaultName: "회귀자",
      age: "나이",
      gender: "성별",
      genderMale: "남성",
      genderFemale: "여성",
      genderPrivate: "비공개",
      country: "국가",
      countryKorea: "대한민국",
      countryUsa: "미국",
      countryJapan: "일본",
      countryChina: "중국",
      countryOther: "기타",
      quizEyebrow: "성향 분석",
      q1: "쓰러져 있는 사람을 발견했다. 당신의 행동은?",
      q1Hero: "대가 없이 즉시 돕는다.",
      q1Pragmatic: "위험과 보상을 확인하고 돕는다.",
      q1Vengeful: "원인을 찾아 대가를 치르게 할 준비를 한다.",
      q2: "공동체의 규칙과 낯선 시험의 규칙에 대해 어떻게 생각하는가?",
      q2Lawful: "사회 유지를 위해 반드시 지켜야 한다.",
      q2Pragmatic: "상황에 따라 융통성 있게 적용해야 한다.",
      q2Chaotic: "규칙은 약자들의 핑계일 뿐이다.",
      q3: "강력한 힘을 얻기 위해 타인을 희생해야 한다면?",
      q3Hero: "어떤 경우에도 타인을 희생시킬 수 없다.",
      q3Pragmatic: "더 큰 피해를 막기 위한 선택이라면 검토한다.",
      q3Vengeful: "나의 성장을 위해서라면 기꺼이 밟고 올라선다.",
      q4: "함께 움직이던 무리의 지휘자가 부당한 지시를 내렸다.",
      q4Lawful: "원칙에 따라 명령에 복종한다.",
      q4Pragmatic: "내 이익에 부합하는지 먼저 따져본다.",
      q4Chaotic: "즉각 반발하고 독자적으로 행동한다.",
      q5: "당신이 궁극적으로 바라는 세계의 모습은?",
      q5Hero: "모두가 억압받지 않는 평화로운 세계",
      q5Pragmatic: "간섭받지 않는 철저한 개인주의적 세계",
      q5Chaotic: "절대적인 강자가 통제하는 힘의 세계",
      submit: "세계선 동기화",
    },
    app: {
      tutorialIsland: "튜토리얼 섬",
      previousTab: "이전 탭",
      nextTab: "다음 탭",
      mainMenu: "주요 메뉴",
      nav: {
        combat: "전투",
        status: "상태",
        inventory: "소지품",
        shop: "상점",
        regions: "지역",
        settings: "설정",
      },
      compactObjective: {
        eyebrow: "목표",
        description: "5개 지역을 돌파하고 검은 균열 관문의 피해량 평가에 도전하세요.",
      },
      systemWindow: {
        title: "각성자 시스템",
        notice: "알림",
        message: "시스템이 회귀자의 기록과 동기화 중입니다.",
        timeline: "세계선 1",
        waiting: "동기화 대기",
      },
      objective: {
        eyebrow: "다음 목표",
        loadingTitle: "다음 개발 확인 중",
        loadingDetail: "성장 목표를 계산하고 있습니다.",
        displayMode: "다음 목표 표시 방식",
        previous: "이전 목표",
        auto: "자동",
        next: "다음 목표",
        collapse: "목표 접기",
      },
      region: {
        eyebrow: "현재 지역",
        defaultTitle: "초심자의 해안",
        defaultLore: "첫 균열이 열린 해안. 약한 마물이 떠밀려온다.",
        level: "레벨",
        rank: "랭크",
        power: "전투력",
        nodeMapPanelTitle: "게이트 노드맵",
        nodeMapEyebrow: "차원 게이트",
        nodeMapWaiting: "노드맵 대기 중",
        nodeMapRegionOnly: "노드맵이 연결된 지역에서 표시됩니다.",
      },
      combat: {
        panelTitle: "전투",
        enemyName: "전투 조율",
        waiting: "대기 중",
        autoToggle: "자동 전투 전환",
        auto: "자동",
        rest: "휴식",
        huntToggle: "전투 전환",
        hunt: "전투",
        stage: "전투 무대",
        combo: "연속 0타",
        hyper: "하이퍼 모드 발동",
        playerName: "회귀자",
      },
      status: {
        systemWindowTitle: "각성자 상태창",
        recordEyebrow: "각성자 기록",
        defaultStatusWindow: "회귀자 상태창",
        profileDefaultName: "회귀자",
        portraitLabel: "각성자 이미지",
      },
      profileEdit: {
        panelTitle: "플레이어 정보 변경",
        eyebrow: "플레이어",
        previewAria: "플레이어 이미지 미리보기",
        previewLabel: "각성자",
        adjustImage: "이미지 위치 조정",
        adjustImageHint: "이미지를 드래그하거나 버튼으로 위치와 확대를 조정하세요.",
        moveUp: "위",
        moveDown: "아래",
        moveLeft: "왼쪽",
        moveRight: "오른쪽",
        zoomIn: "확대",
        zoomOut: "축소",
        resetImageFrame: "초기화",
        confirmImageFrame: "위치 확정",
        name: "이름",
        photo: "사진",
        chooseImage: "이미지 찾기",
        defaultImage: "기본 이미지",
        defaultAwakenerImage: "기본 각성자 이미지",
        save: "변경 저장",
      },
    },
  },
  editorStatic: {
    authority: "SYSTEM 권한",
    title: "Project Regressor 에디터 준비실",
    description: "현재는 게임 데이터를 직접 바꾸지 않는 읽기 중심 화면입니다. 에디터에 연결할 위치, 파일명, 세이브 키, 미뤄둔 작업을 한곳에서 확인합니다.",
    backToGame: "게임으로 돌아가기",
    panelListAria: "에디터 패널 목록",
    preparedPanels: "준비된 패널",
    connection: "연결 상태",
    loadingTitle: "에디터 데이터를 불러오는 중",
    loadingCopy: "manifest와 backlog를 확인하고 있습니다.",
    panelDetails: "패널 세부 정보",
    assetEyebrow: "이미지/사운드",
    fileSlots: "파일 슬롯",
    fileSlotsCopy: "같은 이름의 파일을 지정 폴더에 넣으면 추후 에디터가 자동 연결할 수 있도록 준비한 목록입니다.",
    saveEyebrow: "세계선",
    saveKeys: "현재 브라우저 저장 키",
    saveKeysCopy: "이 화면은 저장값을 수정하지 않고 존재 여부와 크기만 확인합니다.",
    downloadSaveSummary: "저장 요약 다운로드",
    refresh: "다시 확인",
    prototypeEyebrow: "프로토타입 메모리",
    prototypeTitle: "반드시 남겨둘 관리 목록",
    prototypeCopy: "첨부한 프로토타입 화면에서 UI가 아니라 기능 목록만 추린 항목입니다.",
    backlogEyebrow: "업데이트 대기열",
    backlogTitle: "에디터 반영 목록",
    backlogCopy: "게임 기능을 먼저 만들고, 나중에 에디터를 업데이트할 때 한 번에 처리할 항목들입니다.",
    downloadManifest: "manifest 다운로드",
    downloadBacklog: "backlog 다운로드",
  },
  characterCreation: {
    statLabels: {
      STR: "근력",
      AGI: "민첩",
      VIT: "체력",
      INT: "지능",
      WIS: "정신",
      LUK: "행운",
    },
    profile: {
      title: "시스템 동기화",
      description: "튜토리얼 시스템 내부 식별용 임시 프로필을 스캔합니다.",
      hunterName: "시스템 등록명",
      age: "나이",
      gender: "성별",
      country: "국가",
      profileImage: "프로필 이미지",
      chooseImage: "이미지 찾기",
      nextStep: "다음 단계",
      defaultName: "회귀자",
      emptyImage: "선택한 이미지 없음",
      storedImage: "저장된 이미지 사용 중",
      defaultAwakenerImage: "기본 각성자 이미지",
      imageTooLarge: "이미지 파일은 1.2MB 이하만 사용할 수 있습니다.",
      imageTypeTooLarge: "이미지는 1.2MB 이하의 PNG/JPG/WebP/GIF 파일만 사용할 수 있습니다.",
      adjustImage: "이미지 위치 조정",
      adjustImageHint: "이미지를 드래그하거나 버튼으로 위치와 확대를 조정하세요.",
      moveUp: "위",
      moveDown: "아래",
      moveLeft: "왼쪽",
      moveRight: "오른쪽",
      zoomIn: "확대",
      zoomOut: "축소",
      resetImageFrame: "초기화",
      genderOptions: ["남성", "여성", "비공개"],
      countryOptions: ["대한민국", "미국", "일본", "중국", "기타"],
    },
    stats: {
      title: "기본 능력치 동기화",
      description: "주사위와 동기화 결과에 따라 첫 각성자 프로필의 능력치가 확정됩니다.",
      rollDice: "기본 능력치 확인",
      waiting: "동기화 대기 중",
      complete: "기본 스탯 확정",
      confirmNext: "확정하고 다음으로",
      total: "총합",
      totalWithBaseline: "총합 {total} · 기준 {baseline}",
    },
    questions: {
      title: "심연의 질문",
      description: "당신의 성향을 파악하기 위해 시스템이 질문합니다.",
      replay: "질문 다시 보기",
      items: [
        {
          id: "q1",
          question: "쓰러져 있는 사람을 발견했다. 당신의 행동은?",
          options: [
            ["hero", "대가 없이 즉시 돕는다."],
            ["pragmatic", "위험과 보상을 확인하고 돕는다."],
            ["vengeful", "원인을 찾아 대가를 치르게 할 준비를 한다."],
          ],
        },
        {
          id: "q2",
          question: "공동체의 규칙과 낯선 시험의 규칙에 대해 어떻게 생각하는가?",
          options: [
            ["lawful", "사회 유지를 위해 반드시 지켜야 한다."],
            ["pragmatic", "상황에 따라 융통성 있게 적용해야 한다."],
            ["chaotic", "규칙은 약자들의 핑계일 뿐이다."],
          ],
        },
        {
          id: "q3",
          question: "강력한 힘을 얻기 위해 타인을 희생해야 한다면?",
          options: [
            ["hero", "어떤 경우에도 타인을 희생시킬 수 없다."],
            ["pragmatic", "더 큰 피해를 막기 위한 선택이라면 검토한다."],
            ["vengeful", "나의 성장을 위해서라면 기꺼이 밟고 올라선다."],
          ],
        },
        {
          id: "q4",
          question: "함께 움직이던 무리의 지휘자가 부당한 지시를 내렸다.",
          options: [
            ["lawful", "원칙에 따라 명령에 복종한다."],
            ["pragmatic", "내 이익에 부합하는지 먼저 따져본다."],
            ["chaotic", "즉각 반발하고 독자적으로 행동한다."],
          ],
        },
        {
          id: "q5",
          question: "당신이 궁극적으로 바라는 세계의 모습은?",
          options: [
            ["hero", "모두가 억압받지 않는 평화로운 세계"],
            ["pragmatic", "간섭받지 않는 철저한 개인주의적 세계"],
            ["chaotic", "절대적인 강자가 통제하는 힘의 세계"],
          ],
        },
      ],
    },
    starterCards: {
      title: "운명 카드",
      description: "기본 공격은 확정 등록되고, 추가로 스타터 특성과 스타터 스킬을 선택합니다.",
      basicAttackGuaranteed: "기본 공격은 확정 등록됩니다. 선택한 카드 스킬은 슬롯 1에 함께 등록됩니다.",
      confirmNext: "카드 확정",
      selectedCard: "선택 카드",
      selectedTrait: "특성",
      selectedSkill: "카드 스킬",
      unlock: "해금",
      traitSkill: "{trait} / {skill}",
      items: [
        {
          id: "starter_weapon_sense",
          card: "낡은 무기 감각",
          traitId: "lower_weapon_mastery",
          trait: "하급 무기 숙련",
          skill: "강타",
          actionId: "power_slash",
          glow: "푸른빛",
          unlock: "1회차",
        },
        {
          id: "starter_light_step",
          card: "가벼운 발걸음",
          traitId: "lower_mobility_sense",
          trait: "하급 기동 감각",
          skill: "빠른 발놀림",
          actionId: "quick_step",
          glow: "푸른빛",
          unlock: "1회차",
        },
        {
          id: "starter_enduring_body",
          card: "버티는 몸",
          traitId: "lower_survival_sense",
          trait: "하급 생존 감각",
          skill: "방어 자세",
          actionId: "guard_stance",
          glow: "푸른빛",
          unlock: "1회차",
        },
        {
          id: "starter_faint_mana",
          card: "흐릿한 마력 감각",
          traitId: "lower_mana_sense",
          trait: "하급 마력 감각",
          skill: "마력 점화",
          actionId: "mana_ignite",
          glow: "푸른빛",
          unlock: "1회차",
        },
      ],
    },
    result: {
      title: "동기화 완료",
      description: "등록 정보와 기본 카드가 기록되었습니다. 이제 튜토리얼 섬으로 소환됩니다.",
      analysisComplete: "성향 분석 완료",
      systemAlignment: "[ 시스템 ] 동기화 완료. 당신의 성향은 {alignment}입니다.",
      completionMessage: "시스템 등록이 완료되었습니다. 개별 튜토리얼 시험 공간으로 전송됩니다.",
      name: "이름",
      alignment: "성향",
      statTotal: "능력치 총합",
      statusGrade: "상태창 등급",
      starterCard: "기본 카드",
      starterTrait: "스타터 특성",
      starterSkill: "스타터 스킬",
      startRegion: "시작 지역",
      tutorialIsland: "튜토리얼 섬",
      awakeningStart: "각성 시작",
    },
  },
  saveSlots: {
    slot: "차원 슬롯",
    slotShort: "슬롯",
    fallbackSlot: "저장 슬롯",
    emptySlot: "빈 슬롯",
    newGame: "새게임",
    save: "저장",
    load: "불러오기",
    clear: "비우기",
    active: "현재",
    fallbackName: "회귀자",
    levelPrefix: "레벨",
    unknownRegion: "지역 미기록",
    noSaveRecord: "저장 기록 없음",
    emptyHint: "새 운명을 기록할 수 있습니다.",
    lastSync: "마지막 동기화",
    timeUnknown: "시간 미기록",
    clearTitle: "저장 슬롯 비우기",
    clearQuestion: "{slotLabel}의 저장 기록을 정말 지울까요?",
    clearWarning: "삭제된 저장 기록은 되돌릴 수 없습니다. 아래 예 버튼을 5초 동안 계속 누르면 비워집니다.",
    clearHoldConfirm: "예, 5초 누르고 비우기",
    imageTooLarge: "이미지는 1.2MB 이하의 PNG/JPG/WebP/GIF 파일만 사용할 수 있습니다.",
    defaultAwakenerImage: "기본 각성자 이미지",
    noImageSelected: "이미지 선택 없음",
    storedImage: "저장된 이미지 사용 중",
    messages: {
      missingSlot: "저장 슬롯을 찾지 못했습니다.",
      saved: "{slotLabel}에 현재 세계선을 저장했습니다.",
      noRecord: "{slotLabel}에 저장 기록이 없습니다.",
      loaded: "{slotLabel}에서 세계선을 불러왔습니다.",
      empty: "{slotLabel}에 비울 저장 기록이 없습니다.",
      cleared: "{slotLabel} 저장 기록을 비웠습니다. 새게임을 눌러 새 운명을 시작할 수 있습니다.",
      alreadyExists: "{slotLabel}에는 이미 저장 기록이 있습니다. 비운 뒤 새 게임을 시작할 수 있습니다.",
      startNew: "{slotLabel}에서 새 게임을 시작합니다.",
      initialized: "{slotLabel}을 새 세계선으로 초기화했습니다.",
      cancelled: "새게임 시작을 취소했습니다.",
    },
  },
  developerSettings: {
    expMultiplier: {
      label: "경험치 배율",
      description: "테스트 진행 속도를 조절합니다.",
    },
    outgoingDamageInfinite: {
      label: "주는 데미지 무한",
      description: "플레이어 공격이 적의 현재 체력을 크게 넘기도록 처리합니다.",
    },
    incomingDamageZero: {
      label: "받는 데미지 0",
      description: "몬스터 공격 피해를 0으로 고정합니다.",
    },
    itemDropMultiplier: {
      label: "아이템 드랍율 배율",
      description: "몬스터 드랍 판정 확률을 배수로 올립니다.",
    },
    goldDropMultiplier: {
      label: "골드 드랍율 배율",
      description: "전투와 오프라인 보상의 골드를 배수로 올립니다.",
    },
    skipRegion: {
      label: "현재 지역 스킵",
      description: "현재 지역을 완료 처리하고 다음 지역으로 이동합니다.",
      button: "지역 스킵",
    },
  },
  infoText: {
    "profile:name": [
      "이름",
      "캐릭터의 표시 이름입니다. 상태창, 전투 기록, 알림에서 플레이어를 식별할 때 사용합니다."
    ],
    "profile:level": [
      "레벨",
      "현재 성장 단계입니다. 레벨이 오르면 기본 능력치와 자유 스탯 포인트를 얻습니다."
    ],
    "profile:job": [
      "직업",
      "현재 각성자의 기본 분류입니다. 직업/클래스 시스템은 MVP 이후 확장 예정입니다."
    ],
    "profile:title": [
      "칭호",
      "특정 업적이나 사건으로 붙는 별칭입니다. 현재는 표시용 자리만 유지합니다."
    ],
    "profile:ageGender": [
      "나이/성별",
      "캐릭터 생성 정보입니다. 현재 전투 공식에는 사용하지 않습니다."
    ],
    "profile:country": [
      "국가",
      "캐릭터 생성 때 입력한 국가 정보입니다. 현재 전투 공식에는 사용하지 않습니다."
    ],
    "profile:organization": [
      "단체",
      "현재는 무소속으로 표시되는 확장용 자리입니다. 공식 조직 정보는 튜토리얼 이후에 열립니다."
    ],
    "profile:alignment": [
      "성향",
      "캐릭터의 선택 성향을 요약합니다. 현재는 표시용이며 추후 이벤트 분기에 활용할 수 있습니다."
    ],
    "profile:starterCard": [
      "기본 카드",
      "심연의 질문 이후 선택한 스타터 카드 기록입니다. 새 게임 생성 시 선택한 카드 스킬이 슬롯 1에 함께 등록됩니다."
    ],
    "profile:starterSkill": [
      "카드 스킬",
      "기본 카드와 함께 기록된 스타터 스킬입니다. 기본 공격은 별도로 항상 보장됩니다."
    ],
    "stat:STR": [
      "근력",
      "물리 공격력과 전투력에 직접 영향을 줍니다. 무기 공격 기반 캐릭터의 기본 성장 축입니다."
    ],
    "stat:AGI": [
      "민첩",
      "공격속도, 회피율, 명중률에 영향을 줍니다. 빠르게 때리고 덜 맞는 방향의 성장 축입니다."
    ],
    "stat:VIT": [
      "체력",
      "최대 HP, HP 재생, 방어력, 상태이상 저항 일부에 영향을 줍니다. 버티는 힘을 올립니다."
    ],
    "stat:INT": [
      "지능",
      "마법 공격력과 MP에 영향을 줍니다. 마력탄 같은 마법 계열 성장에 중요합니다."
    ],
    "stat:WIS": [
      "정신",
      "MP, MP 재생, 방어력, 상태이상 저항에 영향을 줍니다. 안정성과 지속 전투력을 올립니다."
    ],
    "stat:LUK": [
      "행운",
      "치명타 확률, 치명타 피해, 드랍률, 명중 보정에 영향을 줍니다. 레벨업 자동 상승은 없고 자유 스탯으로만 올릴 수 있습니다."
    ],
    "derived:hp": [
      "HP",
      "피해를 버틸 수 있는 체력입니다. 0이 되면 전투에서 쓰러지고 회복 처리가 필요합니다."
    ],
    "derived:mp": [
      "MP",
      "강타, 마력탄, 응급 회복 같은 스킬 사용에 필요한 자원입니다."
    ],
    "derived:hpRegen": [
      "HP 재생",
      "초당 회복되는 HP입니다. 휴식 상태에서는 회복 효율이 더 좋아집니다."
    ],
    "derived:mpRegen": [
      "MP 재생",
      "초당 회복되는 MP입니다. 긴 자동 전투에서 스킬 사용 빈도를 받쳐줍니다."
    ],
    "derived:attack": [
      "공격력",
      "기본 공격과 물리 계열 스킬 피해에 영향을 줍니다. 근력, 장비 공격력, 레벨이 주요 원천입니다."
    ],
    "derived:magicAttack": [
      "마법 공격력",
      "마법 계열 스킬 피해에 영향을 줍니다. 지능, 정신, 레벨이 주요 원천입니다."
    ],
    "derived:defense": [
      "방어력",
      "받는 피해를 줄이는 방어 능력입니다. 체력, 정신, 장비 방어가 주요 원천입니다."
    ],
    "derived:critRate": [
      "치명타 확률",
      "공격이 치명타로 들어갈 확률입니다. 행운이 높을수록 증가합니다."
    ],
    "derived:critDamage": [
      "치명타 피해",
      "치명타가 발생했을 때 추가로 커지는 피해 배율입니다. 행운이 높을수록 증가합니다."
    ],
    "derived:attackSpeed": [
      "공격속도",
      "초당 공격 준비 속도입니다. 높을수록 기본 공격과 자동 전투 템포가 빨라집니다."
    ],
    "derived:evade": [
      "회피율",
      "적 공격을 피할 확률입니다. 민첩이 높을수록 증가합니다."
    ],
    "derived:accuracy": [
      "명중률",
      "공격이 빗나가지 않을 확률입니다. 민첩과 행운이 보정합니다."
    ],
    "derived:statusResist": [
      "상태이상 저항",
      "기절, 빙결, 중독, 화상, 감전, 침묵, 공포, 혼란, 수면 같은 상태이상에 대한 저항 수치입니다."
    ],
    "derived:dropRate": [
      "드랍률",
      "장비와 보상이 떨어질 확률 보정입니다. 행운이 높을수록 증가합니다."
    ],
    "derived:exp": [
      "경험치",
      "필요 경험치에 도달하면 레벨업합니다. 레벨업 시 근력/민첩/체력/지능/정신 +1, 자유 스탯 +2를 획득합니다."
    ],
    "derived:freePoints": [
      "보유 포인트",
      "원하는 기본 스탯에 직접 투자할 수 있는 자유 스탯 포인트입니다. + / - 버튼으로 확정 전 배분을 1씩 조정하고, 포인트가 10 이상이면 +10 / -10 버튼으로 크게 조정합니다. 배분 확정 후에는 다음 레벨업 전까지 해당 포인트를 되돌릴 수 없습니다."
    ],
    "derived:recommendedAllocation": [
      "추천 분배",
      "현재 보유 포인트를 자동 전투에 무난한 방향으로 한 번에 배분합니다."
    ],
    "resistance:physical": [
      "물리 저항",
      "물리 피해 저항용 예약 슬롯입니다. 전설 장비/버프 옵션으로 확장할 예정이며 현재 전투 공식에는 아직 적용하지 않습니다."
    ],
    "resistance:fire": [
      "화염 저항",
      "화염 피해 저항용 예약 슬롯입니다. 전설 장비/버프 옵션으로 확장할 예정입니다."
    ],
    "resistance:cold": [
      "냉기 저항",
      "냉기 피해 저항용 예약 슬롯입니다. 전설 장비/버프 옵션으로 확장할 예정입니다."
    ],
    "resistance:lightning": [
      "번개 저항",
      "번개 피해 저항용 예약 슬롯입니다. 전설 장비/버프 옵션으로 확장할 예정입니다."
    ],
    "resistance:wind": [
      "바람 저항",
      "바람 피해 저항용 예약 슬롯입니다. 전설 장비/버프 옵션으로 확장할 예정입니다."
    ],
    "resistance:earth": [
      "대지 저항",
      "대지 피해 저항용 예약 슬롯입니다. 전설 장비/버프 옵션으로 확장할 예정입니다."
    ],
    "resistance:poison": [
      "독 저항",
      "독 피해 저항용 예약 슬롯입니다. 상태이상 저항과는 별개로, 속성 피해 저항 자리입니다."
    ],
    "resistance:light": [
      "빛 저항",
      "빛 속성 피해 저항용 예약 슬롯입니다. 전설 장비/버프 옵션으로 확장할 예정입니다."
    ],
    "resistance:dark": [
      "어둠 저항",
      "어둠 속성 피해 저항용 예약 슬롯입니다. 전설 장비/버프 옵션으로 확장할 예정입니다."
    ],
    "resistance:holy": [
      "신성 저항",
      "후반 콘텐츠용 예약 저항입니다. 현재는 표시 자리만 유지합니다."
    ],
    "slot:Weapon": [
      "무기",
      "공격력과 기본 공격 이펙트에 가장 직접적으로 영향을 주는 장비 슬롯입니다."
    ],
    "slot:Helmet": [
      "투구",
      "머리 방어구 슬롯입니다. 방어력과 보조 옵션이 붙을 수 있습니다."
    ],
    "slot:Armor": [
      "갑옷",
      "몸통 방어구 슬롯입니다. 방어력과 생존 옵션이 붙기 좋은 자리입니다."
    ],
    "slot:Gloves": [
      "장갑",
      "손 방어구 슬롯입니다. 공격 능력이나 민첩 관련 옵션이 붙기 좋은 자리입니다."
    ],
    "slot:Boots": [
      "신발",
      "발 방어구 슬롯입니다. 민첩, 회피, 이동 계열 옵션이 붙기 좋은 자리입니다."
    ],
    "slot:Necklace": [
      "목걸이",
      "보조 장신구 슬롯입니다. 마력, 정신, 특수 옵션이 붙기 좋은 자리입니다."
    ],
    "slot:Ring1": [
      "반지 1",
      "반지 장비 슬롯입니다. 반지는 두 개까지 장착할 수 있습니다."
    ],
    "slot:Ring2": [
      "반지 2",
      "반지 장비 슬롯입니다. 반지는 두 개까지 장착할 수 있습니다."
    ]
  },

  helpTextConfig: {
    feedbackOptions: [
      { id: "hit", label: "연속 명중 표시" },
      { id: "damage", label: "피해 숫자 표시" },
      { id: "critical", label: "치명타 표시" },
      { id: "miss", label: "빗나감 표시" },
      { id: "shake", label: "피격 흔들림" },
      { id: "attackEffect", label: "공격 궤적 표시" },
    ],
    combatViewOptions: [
      {
        id: "stageCards",
        label: "무대형 전투 카드",
        description: "HP/MP 숫자를 숨기고 캐릭터 영역을 키워 스프라이트와 배경을 더 크게 보여줍니다.",
      },
      {
        id: "expandedAttackEffects",
        label: "확장 공격 궤적",
        description: "전투 무대 카드 전체를 기준으로 공격 이펙트를 크게 표시합니다. 끄면 기존 초상 영역 기준을 사용합니다.",
      },
      {
        id: "combatLogColors",
        label: "전투 기록 색상 강조",
        description: "전투 기록의 피해, 보상, 성장 정보를 지금처럼 색으로 구분합니다. 끄면 예전처럼 단색으로 표시합니다.",
      },
      {
        id: "resourcePercentText",
        label: "HP/MP 퍼센트 표시",
        description: "전투 화면의 플레이어와 몬스터 HP/MP 수치를 현재값/최대값 대신 퍼센트로 표시합니다.",
      },
      {
        id: "nodeTypeColors",
        label: "노드 타입 색상 표시",
        description: "노드맵에서 공개된 노드의 타입을 색상으로 구분합니다. 끄면 공개된 노드도 중립색으로 표시합니다.",
      },
      {
        id: "fieldInfoTooltips",
        label: "항목 설명 표시",
        description: "스탯, 전투 스탯, 저항, 장비, 아이템 이름에 커서를 올리거나 클릭했을 때 설명창을 표시합니다.",
      },
      {
        id: "touchDoubleTapActions",
        label: "터치 버튼 두 번 실행",
        description:
          "터치 환경에서 설명이 있는 실행 버튼을 한 번 누르면 설명만 보여주고, 같은 버튼을 한 번 더 누르면 실행합니다. 끄면 기존처럼 길게 눌러 설명을 봅니다.",
      },
    ],
    helpText: {
      rest: ["휴식", "전투 지역에서 완전히 이탈해 HP와 MP를 빠르게 회복합니다. 자동 전투 재시작은 휴식 중에는 잠시 멈춥니다."],
      autoHunt: ["자동 전투", "켜두면 현재 지역에서 전투가 끝난 뒤 다음 전투를 자동으로 이어갑니다."],
      boss: ["지역 보스 도전", "현재 지역의 보스가 있을 때 보스전을 시작합니다. 일반 전투보다 위험하지만 보상이 큽니다."],
      "stance-conserve": ["보존", "마나와 생존을 아끼는 전술입니다. 위험할 때 응급 회복 같은 지원 행동이 우선됩니다."],
      "stance-power": ["전력", "기본 전투 전술입니다. 조건이 맞으면 공격 스킬을 자동으로 섞어 씁니다."],
      "stance-berserk": ["폭주", "극한 동기화 준비 상태를 활용하는 공격적인 전술입니다. 강하지만 자원 관리가 중요합니다."],
      hit: ["연속 명중 표시", "연속 명중 수를 전투 화면에 표시합니다."],
      damage: ["피해 숫자 표시", "공격, 회복, 피해량 숫자를 전투 화면에 표시합니다."],
      critical: ["치명타 표시", "치명타가 발생했을 때 별도 문구를 표시합니다."],
      miss: ["빗나감 표시", "공격이 빗나갔을 때 빗나감 문구를 표시합니다."],
      shake: ["피격 흔들림", "피격 시 전투 대상 카드가 짧게 흔들립니다."],
      attackEffect: ["공격 이펙트 표시", "기본 공격과 스킬 타격 궤적을 표시합니다."],
    },
    basicAttackAction: {
      id: "basic_attack",
      name: "기본 공격",
      mpCost: 0,
      damageType: "basic",
      stanceAllowed: ["conserve", "power", "berserk"],
      triggerCondition: "always",
      description: "현재 전술의 빈틈을 채우는 평타입니다. 마나를 소모하지 않습니다.",
    },
    actionTriggerText: {
      basicAttack: "공격 게이지 100% 도달 시",
      playerHpBelow45: "체력 45% 이하일 때 자동 사용",
      playerHpBelow30: "체력 30% 이하일 때 자동 사용",
      stanceAutoSuffix: "전술에서 조건 충족 시 자동 사용",
    },
    combatInfoHideHint: "커서가 벗어나거나 길게 누르기를 끝내면 설명이 사라집니다.",
  },
  inventoryUi: {
    separator: " · ",
    valuePositive: "가치 +{value}",
    valueNegative: "가치 {value}",
    sameValue: "동급",
    equip: "장착",
    replace: "교체",
    unequip: "해제",
    buy: "구매",
    sell: "매각",
    equippedSummary: "{equipped} / {total} 장착",
    inventorySummary: "{types}종 · {total}개 · {recommendedText}",
    recommendedCount: "추천 {count}개",
    noRecommended: "추천 없음",
    noAcquiredEquipment: "획득 전리품 없음",
    recommendEquip: "추천 장착",
    recommendEquipCount: "추천 장착 ({count})",
    emptyEquipmentList: "아직 획득한 전리품이 없습니다.",
    emptySlot: "빈 슬롯",
    emptyEquipped: "비어 있음",
    equipped: "장착",
    itemIcon: "{name} 아이콘",
    emptyItemIcon: "{name} 빈 아이콘 슬롯",
    unequipAria: "{name} 해제",
    itemInfoSummary: "{rarity} {slotName} 장비입니다.",
    itemInfoEffect: "효과: {effect}",
    itemInfoFallback: "세부 고유 설명은 추후 장비 옵션 확장 때 추가됩니다.",
    lootItem: "전리품",
    lootItemInfoSummary: "{rarity} {type}입니다.",
    lootItemInfoFallback: "세부 사용처는 추후 전리품 제작/도감 확장 때 추가됩니다.",
    shopItemInfoFallback: "자세한 설명은 추후 장비 도감 확장 때 추가됩니다.",
    shopGoldSummary: "보유 골드 {gold} G",
    emptyShopStock: "등록된 상점 상품이 없습니다.",
    emptySellList: "매각할 보관 장비가 없습니다.",
    shopFallbackCategory: "상점",
    shopFallbackNote: "차원 보급소에 등록된 장비입니다.",
    equipmentFallback: "장비",
    slotMarks: {
      Weapon: "검",
      Helmet: "투",
      Armor: "갑",
      Gloves: "장",
      Boots: "신",
      Necklace: "목",
      Ring: "반",
      codex_fragment: "도",
      mana_crystal: "석",
      skill_fragment: "술",
    },
    rarityLabels: {
      common: "일반",
      uncommon: "고급",
      rare: "희귀",
      heroic: "영웅",
      legendary: "전설",
    },
  },
  buildInfo: {
    cacheVersion: "캐시 v{version}",
    cacheCheckNeeded: "캐시 확인 필요",
  },
  dropPreview: {
    empty: "확인된 드랍 없음",
    valueUpgrade: " · 가치 +{delta}",
    lootType: " · {type}",
  },
  growthObjective: {
    eyebrowDefault: "다음 목표",
    eyebrowIndexed: "다음 목표 {current}/{total}",
    expandLabel: "{title} 펼치기",
    collapseLabel: "{title} 접기",
    manual: "수동",
    automatic: "자동",
    enableAutoRotation: "다음 목표 자동 순환 켜기",
    switchToManual: "다음 목표 수동 전환",
  },
  panels: {
    defaultTitle: "창",
    expandLabel: "{title} 펼치기",
    collapseLabel: "{title} 접기",
  },
  combatActions: {
    skillLoadoutTabsLabel: "스킬 슬롯 선택",
    unavailableReason: "현재 {reason}",
  },
  combatVitals: {
    waiting: "대기",
    defeated: "처치 완료",
    enemyLevel: "레벨 {level} · {name}",
  },
  equipmentActions: {
    equipped: "{itemName} 장착.",
    unequipped: "{itemName} 해제.",
    attack: "공격",
    defense: "방어",
    stanceChanged: "전술 스탠스 변경: {stanceLabel}.",
  },
  stateMessages: {
    restRecovered: "짧은 휴식으로 HP를 회복했습니다.",
    levelReached: "레벨 {level} 달성. 근력/민첩/체력/지능/정신 +1, HP/MP 회복, 자유 스탯 +2.",
    noRecommendedEquipment: "추천 장착할 더 좋은 장비가 없습니다.",
    recommendedEquipmentMore: " 외 {count}개",
    recommendedEquipmentDone: "추천 장착 완료: {items}{suffix}.",
    defeatRecovered: "쓰러졌지만 사망하지 않았습니다. 휴식 후 다시 도전하세요.",
    regionRisk: " 권장 레벨 {level}보다 낮으므로 매우 위험합니다.",
    regionMoved: "{regionName}으로 이동했습니다.{riskText}",
    lootInsight: "장비 후보 감지: {itemName} 장비 가치 +{delta}. 소지품의 추천 장착으로 확인하십시오.",
    fallbackEquipment: "새 장비",
    autoHuntEnabled: "자동 전투 모듈이 활성화되었습니다.",
    autoHuntDisabled: "자동 전투 모듈이 비활성화되었습니다.",
    initialLog: "시스템 동기화가 완료되었습니다. 초심자의 해안으로 전송된 뒤, 상태창의 기본 정보가 활성화되었습니다.",
    offlineReward: "오프라인 자동 전투 보상: {minutes}분, {kills}회 처치 추정, 경험치 {exp}, 골드 {gold} 획득.",
    offlineExtraLoot: "오프라인 자동 전투 추가 획득: {summary}.",
    firstSync: "{name}의 첫 세계선이 동기화되었습니다. 성향: {alignment}. 기본 카드: {starterCard}.",
    noStarterCard: "미등록",
    noStarterSkill: "미등록",
    tutorialTransfer: "[전송] 개별 튜토리얼 시험 공간으로 좌표를 고정합니다.",
    tutorialStatAssignment: "[초기 능력치] 능력치: {statSummary}. 능력치 총합: {statTotal}. 상태창 등급: {statusGrade}.",
    tutorialLocation: "[지역] {regionName}. 첫 균열이 열린 해안. 약한 마물이 떠밀려옵니다.",
    tutorialStatusBriefing: "[상태창] 기본 정보가 활성화되었습니다. 상태창 등급: {statusGrade}. 확정 스킬: 기본 공격. 카드 스킬: {starterSkillName}.",
    firstCombatWarning: "[경고] 적성 개체가 접근합니다.",
    firstCombatBasicGuide: "[전투 도움말] 기본 공격은 MP를 소모하지 않습니다.",
    firstCombatSkillGuide: "[전투 도움말] 카드 스킬은 조건과 MP를 확인한 뒤 자동으로 사용됩니다.",
    profileUpdated: "플레이어 정보 변경사항을 저장했습니다.",
  },
  story: {
    tutorialDialogue: {
      rules: {
        version: "v2.6.3_FINAL",
        dynamicPlaceholders: [
          "playerName",
          "dispositionName",
          "statSummary",
          "statTotal",
          "statusGrade",
          "STR",
          "AGI",
          "VIT",
          "INT",
          "WIS",
          "LUK",
          "starterTraitName",
          "starterSkillName",
        ],
        preRealityForbiddenTerms: {
          hunterAssociation: "헌터협회",
          hunterAssociationSpaced: "헌터 협회",
          hunterRegistrationName: "헌터 등록명",
          hunterGrade: "헌터 등급",
          guildAffiliation: "소속 길드",
          guildMaster: "길드 마스터",
          hunterFreeBoard: "헌터 자유게시판",
        },
      },
      introLog: {
        disposition: "[성향 반응] {disposition}. {reaction}",
        starterCard: "[운명 카드] {cardName}. {reaction}",
      },
      dispositions: {
        devotedOrder: {
          name: "헌신 질서",
          log: "시스템이 보호와 질서를 우선하는 판단 패턴을 기록했습니다.",
        },
        practicalBalance: {
          name: "실용 균형",
          log: "시스템이 위험과 보상을 함께 계산하는 판단 패턴을 기록했습니다.",
        },
        coldCalculation: {
          name: "냉정 계산",
          log: "시스템이 감정보다 생존 확률을 앞세우는 판단 패턴을 기록했습니다.",
        },
        freeSurvival: {
          name: "자율 생존",
          log: "시스템이 규칙보다 현장 생존을 우선하는 판단 패턴을 기록했습니다.",
        },
        inquiryRecord: {
          name: "탐구 기록",
          log: "시스템이 관찰과 기록을 우선하는 판단 패턴을 기록했습니다.",
        },
      },
      starterCards: {
        weaponSense: {
          cardName: "낡은 무기 감각",
          log: "손에 익은 무게가 먼저 반응합니다. 슬롯 1에 강타가 연결됩니다.",
        },
        lightStep: {
          cardName: "가벼운 발걸음",
          log: "균열 지형을 읽는 감각이 깨어납니다. 슬롯 1에 빠른 발놀림이 연결됩니다.",
        },
        enduringBody: {
          cardName: "버티는 몸",
          log: "첫 시험의 충격을 받아낼 준비가 끝났습니다. 슬롯 1에 방어 자세가 연결됩니다.",
        },
        faintMana: {
          cardName: "흐릿한 마력 감각",
          log: "희미한 마력 회로가 열린 채 동기화됩니다. 슬롯 1에 마력 점화가 연결됩니다.",
        },
      },
      keyEvents: {
        northRockGoldCardHint: "북쪽 바위 틈에서 황금빛 카드의 위치만 기록됩니다. 1회차에는 획득하지 못합니다.",
        alphaWolfElite: "그림자 늑대 우두머리는 회피하거나 재도전할 수 있는 첫 엘리트 전투입니다.",
        hiddenStairLocked: "무너진 탑의 숨은 계단은 조건을 모르면 열리지 않습니다.",
        sealedBoxLocked: "마석 광산의 봉인 상자는 기록 조건이 없으면 반응만 남깁니다.",
        coreGolemHiddenElite: "광산 심부의 핵 골렘은 숨겨진 엘리트 전투 후보입니다.",
        forgottenGodRemnant: "잊힌 신의 잔재는 회귀의 원인을 암시하지만 1회차에는 이해할 수 없습니다.",
        run2GoldenCard: "2회차 이후 황금 카드가 회귀자의 기록으로 실체화됩니다.",
        run2SealedBox: "2회차 이후 봉인 상자가 기록 조건으로 열립니다.",
        run4WardenClear: "최종 관문 파수꾼은 누적 성장으로 완전 돌파합니다.",
      },
      keyEventDetails: {
        shoreStatusHelp: {
          title: "상태창 재확인",
          systemLines: [
            "[상태창] 기본 정보가 활성화됩니다.",
            "레벨: 1. 상태창 등급: {statusGrade}. 능력치: {statSummary}. 확정 스킬: 기본 공격. 카드 스킬: {starterSkillName}.",
            "[안내] 본 시험의 목표는 생존과 최종 관문 평가 조건 달성입니다.",
            "[주의] 본 시험은 생명 활동의 안전을 보장하지 않습니다.",
          ],
          protagonistLines: [
            "숫자가 낮다는 건 알겠다.",
            "기본 공격 하나와 카드로 받은 스킬 하나.",
            "이걸로 버텨야 한다는 거군.",
          ],
        },
        driftSlimeManaVariant: {
          title: "표류 점액체",
          commonLines: [
            "[미확인 몬스터] 표류 점액체.",
            "[위협 태그 후보] 점액형 / 마법취약.",
          ],
          manaIgniteLines: [
            "저건 물리로 때리면 잘 안 먹힐 것 같은데.",
            "[스킬 안내] 마력 점화는 약한 마력 피해를 줍니다.",
            "좋아. 카드로 고른 게 여기서 의미가 있나 보자.",
          ],
          noManaIgniteLines: [
            "무기로 공격하는 감각이 이상하다.",
            "물리 공격이 전부 정답은 아니라는 뜻인가.",
            "[패턴 기록] 표류 점액체는 마력 계열 공격에 취약할 가능성이 있습니다.",
          ],
        },
      },
      loop5Plus: {
        optimization: {
          name: "침착한 최적화",
          wake: ["또 해안이다.", "감정은 줄이고, 동선만 남긴다.", "이번 목표는 기록 단축과 다음 재앙 준비."],
          boss: ["파수꾼의 패턴은 끝까지 기록됐다.", "실수만 없으면 다시 넘긴다."],
        },
        fatigue: {
          name: "피로와 압박",
          wake: ["눈을 뜰 때마다 같은 파도 소리다.", "익숙해졌다고 괜찮은 건 아니다.", "그래도 절차는 지킨다."],
          boss: ["지겹다고 방심하면 죽는다.", "반복은 무기가 되지만, 방심은 독이다."],
        },
        records: {
          name: "기록과 데이터",
          wake: ["도감, 스크랩북, 기록.", "이번엔 어떤 수치가 달라지는지 확인한다.", "감이 아니라 데이터로 움직인다."],
          boss: ["패턴 완성도 100%.", "이번 전투는 검증이다."],
        },
        variables: {
          name: "변수 경계",
          wake: ["같은 해안, 같은 바람.", "하지만 완전히 같은 회차는 없다.", "드랍, 위치, 작은 이동 편차까지 확인한다."],
          boss: ["정해진 패턴이어도 타이밍은 흔들릴 수 있다.", "변수를 남기지 않는다."],
        },
      },
    },
  },
  profile: {
    alignments: {
      neutral: "중립",
      chaoticPragmatic: "혼돈 중립",
      lawfulHero: "질서 선",
      heroLawful: "헌신 질서",
      vengefulChaotic: "복수 혼돈",
      hero: "헌신형",
      pragmatic: "실리형",
      vengeful: "복수형",
      lawful: "질서형",
      chaotic: "혼돈형",
    },
  },
  saveLoad: {
    exportMessage: "저장 파일을 내보냈습니다.",
    importMessage: "저장 파일을 불러왔습니다.",
    importFallbackError: "저장 파일을 불러오지 못했습니다.",
  },
  combatPulse: {
    hitCombo: "연속 {hitCount}타",
    hyperActive: "극한 동기화 발동 중 {seconds}초",
    hyperCooldown: "극한 동기화 냉각 중 {seconds}초",
    hyperReady: "극한 동기화 준비 완료",
    hyperPercent: "극한 동기화 {percent}%",
  },
  resistances: {
    labels: {
      physical: "물리 저항",
      fire: "화염 저항",
      cold: "냉기 저항",
      lightning: "번개 저항",
      wind: "바람 저항",
      earth: "대지 저항",
      poison: "독 저항",
      light: "빛 저항",
      dark: "어둠 저항",
      holy: "신성 저항",
    },
  },
  hyperActions: {
    playerActivated: "극한 동기화 발동. 회귀자의 전투 감각이 가속됩니다.",
    playerEnded: "극한 동기화 종료. 감각 동기화가 잠시 냉각됩니다.",
    enemyActivated: "{monsterName}의 위협 패턴이 폭주합니다.",
    enemyEnded: "{monsterName}의 폭주 패턴이 가라앉았습니다.",
  },
  shopMessages: {
    itemMissing: "상점 상품 정보를 찾을 수 없습니다.",
    buyGoldMissing: "{itemName} 구매 실패. 골드가 {missingGold} G 부족합니다.",
    buyDone: "{itemName} 구매 완료. {price} G를 사용했습니다.",
    sellItemMissing: "매각할 장비 정보를 찾을 수 없습니다.",
    sellNoStock: "{itemName} 매각 실패. 보관 수량이 없습니다.",
    sellDone: "{itemName} 매각 완료. {price} G를 획득했습니다.",
  },
  combatRewards: {
    exp: "경험치 {exp}",
    expWithBase: "경험치 {exp} / {baseExp}",
    lowRiskPenalty: " 낮은 위험도의 반복 사냥이라 경험치 효율이 감소했습니다.",
    devMultiplierBonus: " 개발 테스트 배율이 적용되었습니다.",
    monsterDefeated: "{monsterName} 처치. {expText}, 골드 {gold} 획득.{penaltyText}{bonusText}",
    itemAcquired: "{itemName} 획득.",
    lootItemAcquired: "전리품 획득: {typeLabel} · {itemName}.",
    lootItemFallbackType: "전리품",
    bossCleared: "{regionName}의 보스를 격파했습니다. 튜토리얼 섬의 균열이 약해집니다.",
  },
  combatMessages: {
    basicAttack: "기본 공격",
    criticalPrefix: "치명타! ",
    enemyHyperAttack: "폭주 공격",
    enemyCounter: "반격",
    start: "{monsterName}와 전투를 시작했습니다.",
    stop: "전투를 종료했습니다.",
    heal: "{skillName} 발동. HP {amount} 회복.",
    miss: "{actionName}이 빗나갔습니다.",
    hit: "{criticalText}{actionName}{actionParticle} {monsterName}에게 {damage} 피해.",
    actionParticleConsonant: "으로",
    actionParticleVowel: "로",
    actionParticleDefault: "으로",
    enemyEvade: "{monsterName}의 반격을 회피했습니다.",
    enemyAttack: "{monsterName}의 {attackName}. {damage} 피해를 받았습니다.",
    bossBreak: "BREAK! 보스의 캐스팅이 끊겼습니다.",
  },
  combatLogFormatter: {
    classPatterns: {
      luckyNeedle: "행운",
      luckyReward: "골드|획득|보상",
      critical: "치명타",
      poisonNeedle: "독",
      magicNeedle: "마력탄|마법",
      damageNeedle: "피해",
      reward: "경험치|골드|획득|보상|장비 후보|드랍|추천 장착 완료|오프라인 자동 전투 보상",
      defeat: "처치\\.|격파|사망",
      growth: "레벨|새 지역 개방|스탯|전투력|성장|달성",
      physical: "피해|강타|기본 공격",
      warning: "오류|쓰러졌|실패|부족|잠김|위험|경고|비활성화",
    },
    tokenPatterns: {
      lootItemAcquired: "^(전리품 획득:\\s)([^·.]+?)(\\s·\\s)([^.]+?)(\\.)$",
      itemQuantity: "(^|[:,]\\s)([\\p{Script=Hangul}A-Za-z][\\p{Script=Hangul}A-Za-z0-9·\\s-]*?)\\s(x\\d+)",
      gateRewardItem: "^(게이트 보상 노드에서\\s)([^:,.]+?)(\\s획득\\.)$",
      itemAcquired: "^([^:,.]+?)(\\s획득\\.)$",
      battleStart: "^(.*?)(와 전투를 시작했습니다\\.)$",
      defeated: "^(.*?)( 처치\\.)",
      enemyAction: "^(.*?)(의 반격|의 폭주 공격)",
      targetName: "(으로\\s)(.*?)(에게)",
      systemTokens: "오프라인 자동 전투 추가 획득|오프라인 자동 전투 보상|전투 도움말|카드 스킬|전투를 시작|전투를 종료|자동 전투 모듈|토벌 보상|전리품|장비 후보|드랍|추천 장착 완료|보상",
      skillTokens: "기본 공격|강타|마력탄|응급 회복|빠른 발놀림|방어 자세|마력 점화",
      criticalToken: "치명타!",
      damage: "(\\d[\\d,]*\\s피해)",
      heal: "((?:HP|MP)\\s?\\d[\\d,]*\\s{0,1}회복)",
      exp: "(경험치\\s?\\d(?:[\\d,]*\\d)?)",
      gold: "(골드\\s?\\d(?:[\\d,]*\\d)?)",
      stat: "(자유 스탯\\s?\\+\\d+|능력치 포인트\\s?\\+\\d+|스탯\\s?\\+\\d+|장비 가치\\s?\\+\\d+)",
      growth: "(레벨\\s?\\d+|랭크\\s?[A-Z\\p{Script=Hangul}]+)",
    },
  },
  combatControls: {
    huntStart: "전투 시작",
    huntStop: "전투 종료",
    huntShort: "전투",
    autoOn: "자동 전투 활성",
    autoOff: "자동 전투 중지",
    autoShort: "자동",
    restStart: "휴식",
    restActive: "휴식 중",
    restStartAria: "휴식 시작",
    restStopAria: "휴식 해제",
    restStartTitle: "전투 지역에서 이탈해 HP/MP를 빠르게 회복합니다.",
    restStopTitle: "휴식을 끝내고 전투 대기로 돌아갑니다.",
    statusCombat: "교전 중",
    statusRest: "휴식 중",
    statusAuto: "자동 대기",
    statusManual: "수동 전투",
  },
  combatActionAvailability: {
    onlyCombat: "전투 중에만 사용할 수 있습니다.",
    noMp: "마나가 부족합니다.",
    wrongStance: "{stanceName} 전술에서는 사용할 수 없습니다.",
    lowHp: "체력이 30% 이하일 때 사용할 수 있습니다.",
    berserkNeedHyper: "폭주 전술은 극한 동기화가 준비되어야 공격 스킬을 사용할 수 있습니다.",
    stances: {
      conserve: "보존",
      power: "전력",
      berserk: "폭주",
      break_wait: "브레이크 대기",
    },
  },
  deploymentUpdate: {
    title: "GitHub 배포",
    check: "업데이트 확인",
    apply: "업데이트 적용",
    openPages: "GitHub Pages 열기",
    openRepo: "저장소 열기",
    checking: "GitHub Pages의 최신 버전을 확인하는 중입니다.",
    error: "아직 GitHub Pages 배포 파일을 읽지 못했습니다. 첫 푸시와 Pages 설정 후 다시 확인하세요.",
    preparing: "현재 화면 {displayVersion}. GitHub Pages 배포 준비 중입니다.",
    available: "새 버전 {displayVersion} 사용 가능.",
    current: "최신 배포 기준과 일치합니다. {displayVersion}",
  },
  saveDefaults: {
    playerName: "회귀자",
    gender: "남성",
    country: "대한민국",
    job: "각성자",
    title: "[없음]",
    organization: "무소속",
    alignment: "중립",
    slotName: "슬롯 {number}",
    skillLoadouts: {
      slot1: "슬롯 1",
      slot2: "슬롯 2",
    },
    errors: {
      invalidJson: "저장 파일이 JSON 형식이 아닙니다.",
      missingGameData: "저장 파일에 게임 데이터가 없습니다.",
    },
  },
  gateNodeActions: {
    treasure: "게이트 보상 노드에서 {itemName} 획득.",
    rest: "게이트 안의 안전지대를 확보했습니다. 잠시 숨을 고르고 HP와 MP를 회복합니다.",
    merchant: "차원 틈새의 상인을 만났습니다. 상점 화면은 이후 연결 예정입니다.",
    scene: "{label} 노드에 진입했습니다. 대화/이벤트 선택지 화면으로 연결할 자리입니다.",
    unknownNode: "알 수 없는",
    inspect: "{nodeLabel} 노드를 조사했습니다.",
  },
  gateNodeTypes: {
    start: {
      label: "시작",
      icon: "S",
      description: "게이트 진입 지점입니다. 맵마다 1개를 기본값으로 둡니다.",
    },
    battle: {
      label: "전투",
      icon: "전",
      description: "일반 몬스터 전투 노드입니다. 파밍과 기본 성장 루트를 만듭니다.",
    },
    elite: {
      label: "정예",
      icon: "정",
      description: "일반 전투보다 위험하지만 보상이 큰 노드입니다.",
    },
    boss: {
      label: "보스",
      icon: "보",
      description: "게이트의 최종 전투 노드입니다.",
    },
    hidden_boss: {
      label: "히든 보스",
      icon: "히보",
      description: "조건을 만족하거나 특정 루트를 탔을 때 발견되는 강적 노드입니다.",
    },
    treasure: {
      label: "일반 보물",
      icon: "상",
      description: "확정 또는 높은 확률 보상을 주는 노드입니다.",
    },
    hidden_treasure: {
      label: "히든 보물",
      icon: "히상",
      description: "숨겨진 루트나 조건으로 발견되는 보물 노드입니다.",
    },
    merchant: {
      label: "상인",
      icon: "상인",
      description: "상점 화면으로 연결될 노드입니다. 지금은 로그 결과만 준비합니다.",
    },
    rest: {
      label: "휴식",
      icon: "휴",
      description: "HP와 MP를 회복하는 안전 노드입니다.",
    },
    event: {
      label: "이벤트",
      icon: "사건",
      description: "대화, 선택지, 상태 변화 화면으로 연결될 노드입니다.",
    },
    mystery: {
      label: "미확인",
      icon: "?",
      description: "도착 전까지 정체를 흐리게 보여주는 랜덤/가변 노드입니다.",
    },
    hidden_piece: {
      label: "히든피스",
      icon: "히든",
      description: "회귀 지식이나 조건을 통해 발견하는 특수 단서 노드입니다.",
    },
    hidden: {
      label: "히든",
      icon: "히",
      description: "이전 세이브 호환용 히든 노드입니다. 새 데이터는 hidden_piece 등을 우선 사용합니다.",
    },
  },
  regionUi: {
    moveAria: "{regionName} 지역으로 이동",
    recommendedLine: "권장 레벨 {level} · {description}",
    summaryBlocked: "개방 {open}/{total} · 정화 {cleared} · 현재 게이트 경로 진행 필요",
    summaryHighRisk: "개방 {open}/{total} · 정화 {cleared} · 고위험 {regionName}",
    summaryReady: "개방 {open}/{total} · 정화 {cleared} · 모든 지역 권장 레벨 충족",
    nodeMapTitle: "{regionName} 노드맵",
    nodeMapWaiting: "노드맵 대기 중",
    nodeMapPreview: "게이트 이동 노드는 아직 연결되지 않았지만, 현재 선택한 지역의 지형 기록을 표시합니다.",
    nodeMapRegionOnly: "노드맵이 연결된 지역에서 표시됩니다.",
    unknownWithIndex: "미확인 {index}",
    noMoreNodes: "더 이동할 노드가 없습니다.",
    currentExploration: "현재 탐사 중",
    purified: "정화 완료",
    routeRequired: "현재 경로 진행 필요",
    highRiskMove: "고위험 이동 가능 · 권장 레벨 {level}",
    movable: "이동 가능",
    nodeAria: "{nodeName} 노드",
    stateLine: "붕괴까지 {turn}턴 · 탐사율 {exploration}% · 현재 노드 {nodeName}",
    legendAria: "노드 색상 범례",
    undiscovered: "미확인",
  },
  systemWindow: {
    routinePatterns: [
      "전투를 시작했습니다",
      "전투를 종료했습니다",
      "자동 전투 모듈",
      "기본 공격으로 .* 피해",
      "강타로 .* 피해",
      "마력탄으로 .* 피해",
      "빠른 발놀림으로 .* 피해",
      "마력 점화로 .* 피해",
      "의 반격",
      "빗나갔습니다",
      "회피했습니다",
    ],
    fallbackName: "회귀자",
    unknownRegion: "미확인 지역",
    currentRegion: "현재 지역",
    statusCombat: "교전 중",
    statusIdle: "대기 중",
    playerMeta: "{name} · 레벨 {level}",
    notices: {
        combatLabel: "전투 분석",
        idleLabel: "동기화",
        combatMessage: "전투 데이터를 분석 중입니다. 중요한 변화가 감지되면 이곳에 표시됩니다.",
        idleMessage: "회귀자의 기록을 동기화했습니다.",
        tutorialTransferLabel: "튜토리얼 전송",
        tutorialTransferMessage: "개별 튜토리얼 시험 공간으로 전송되었습니다.",
        tutorialLocationLabel: "지역 확인",
        tutorialLocationMessage: "튜토리얼 시작 지역 정보가 확인되었습니다.",
        tutorialStatusLabel: "상태창 활성화",
        tutorialStatusMessage: "기본 전투 정보가 준비되었습니다.",
        basicAttackReady: "기본 공격 확정",
        cardSkillReady: "카드 스킬 확인",
        checkCombatTab: "전투 탭 확인",
        growthLabel: "성장 알림",
        levelUpMessage: "레벨이 상승했습니다.",
        statUp: "능력치 상승",
      freeStatPlus: "자유 스탯 +2",
      routeLabel: "경로 개방",
      routeMessage: "새 지역 이동 권한이 열렸습니다.",
      checkRegionTab: "지역 탭 확인",
      lootCandidateLabel: "전리품 감지",
      lootCandidateMessage: "더 강한 장비 후보가 감지되었습니다.",
      valuePlus: "가치 +{value}",
      checkInventory: "소지품 확인",
      huntRewardLabel: "토벌 보상",
      huntRewardMessage: "토벌 보상이 정산되었습니다.",
      expMeta: "경험치 {value}",
      goldMeta: "골드 {value}",
      lootLabel: "전리품",
      lootMessage: "전리품을 획득했습니다.",
      clearLabel: "공략 완료",
      clearMessage: "지역 보스 공략 기록이 갱신되었습니다.",
      riftWeakened: "균열 약화",
      warningLabel: "위험 알림",
      systemLabel: "시스템",
    },
    matchers: {
      levelUp: "레벨\\s(\\d+)\\s달성",
      unlockedRegion: "새 지역 개방:\\s(.+?)\\.",
      equipment: "장비 후보 감지:\\s(.+?)\\s장비 가치\\s\\+(\\d+)",
      lootItem: "^전리품 획득:\\s(.+?)\\s·\\s(.+?)\\.",
      reward: "(.+?)\\s처치\\.\\s경험치\\s([\\d,]+),\\s골드\\s([\\d,]+)\\s획득\\.",
      item: "^(.+?)\\s획득\\.",
      bossClear: "보스를 격파했습니다",
      tutorialTransfer: "^\\[전송\\]",
      tutorialLocation: "^\\[지역\\]\\s(.+?)\\.",
      tutorialStatus: "^\\[상태창\\]",
      warning: "쓰러졌|실패|위험|경고|부족|잠김",
    },
  },
  combatReadiness: {
    eyebrow: "준비도",
    bossTitle: "보스 공략",
    bossReadyDetail: "권장 전력권입니다. 장비와 스탯만 확인하고 도전하십시오.",
    bossLockedDetail: "전투력과 레벨을 보강하면 보스 도전 안정성이 오릅니다.",
    damageThresholdBossTitle: "피해량 평가",
    damageThresholdReadyDetail: "제한시간 안에 파수꾼 HP {percent}% 이상을 깎아 통과 조건을 증명하십시오.",
    damageThresholdLockedDetail: "최소 통과 조건은 파수꾼 HP {percent}% 피해량입니다. 전투력과 레벨을 더 보강하십시오.",
    damageThreshold: "목표 피해량 {percent}%",
    recommendedLevel: "권장 레벨 {level}",
    recommendedRank: "권장 랭크 {rank}",
    powerPercent: "전투력 {percent}%",
    finalTitle: "최종 관문",
    finalDetail: "{regionName} 장비를 정비하고 보스 도전을 준비하십시오.",
    levelReady: "권장 레벨 충족",
      rank: "랭크 {rank}",
      nextRegionTitle: "다음 지역",
      nextRegionProgressTitle: "다음 지역 준비",
      nextRegionDetail: "{regionName} 개방까지 경험치 {exp} 필요.",
      targetLevel: "목표 레벨 {level}",
    progress: "{percent}% 달성",
  },
  statusUi: {
    profileFields: {
      name: "이름",
      level: "레벨",
      job: "직업",
      title: "칭호",
      ageGender: "나이/성별",
      country: "국가",
      organization: "단체",
      alignment: "성향",
      starterCard: "기본 카드",
      starterSkill: "카드 스킬",
    },
    noStarterCard: "미등록",
    noStarterSkill: "미등록",
    ageGenderValue: "{age}세 / {gender}",
    portraitAria: "{name} 초상",
    fallbackPortraitName: "플레이어",
    statBatchMinusTitle: "확정 전 임시 배분이 10 이상일 때 한 번에 회수할 수 있습니다.",
    statMinusTitle: "확정 전 배분만 회수할 수 있습니다.",
    derivedLabels: {
      hpRegen: "HP 재생",
      mpRegen: "MP 재생",
      attack: "공격력",
      magicAttack: "마법 공격력",
      defense: "방어력",
      critRate: "치명타 확률",
      critDamage: "치명타 피해",
      attackSpeed: "공격속도",
      evade: "회피율",
      accuracy: "명중률",
      statusResist: "상태이상 저항",
      dropRate: "드랍률",
    },
    perSecond: "{value} / 초",
    perSecondCount: "{value} 회 / 초",
    percent: "{value}%",
    statusWindow: "{name} 상태창",
    level: "레벨 {level}",
    rank: "랭크 {rank}",
    statusGrade: "상태창 등급 {grade}",
    fallbackRank: "F-",
    recommendedAllocation: "추천 분배",
    recommendedAllocationCount: "추천 분배 ({count})",
    freeStatsReset: "임시 배분 초기화",
    freeStatsResetCount: "임시 배분 초기화 ({count})",
    freeStatsConfirm: "배분 확정",
    freeStatsConfirmCount: "배분 확정 ({count})",
  },
  growthObjectiveMessages: {
    statPointsTitle: "스탯 포인트 사용 가능",
    statPointsDetail: "보유 포인트 {points}개. 알림을 눌러 상태창에서 배분하십시오.",
    statusAction: "상태 보기",
    tutorialStartTitle: "튜토리얼 섬 행동 지침",
    tutorialStartDetail: "전투로 지역을 탐색하고, 장비·재료 확보 → 도감 기록 → 최종 관문 20% 피해량을 준비하십시오.",
    finalGateTitle: "최종 관문 공략 가능",
    finalGateDetail: "제한시간 피해량 평가로 검은 관문의 파수꾼에게 성장치를 증명하면 튜토리얼 섬 공략이 끝납니다.",
    regionAction: "지역 보기",
    nextRegionTitle: "다음 개방: {regionName}",
    nextRegionDetail: "레벨 {targetLevel}까지 경험치 {remaining} 필요",
    inventoryAction: "소지품 보기",
    combatAction: "전투 보기",
    notices: {
      region: { title: "지역 정보 갱신" },
      equipment: { title: "장비 정보 갱신" },
      level: { title: "성장 정보 갱신" },
      offline: { title: "오프라인 보상 정산" },
      combat: { title: "전투 상태 갱신" },
    },
    tokens: {
      newRegion: "새 지역",
      unlocked: "개방",
      equipment: "장비",
      recommendedEquip: "추천 장착",
      level: "레벨",
      stat: "스탯",
      offlineReward: "오프라인 자동 전투 보상",
      combatStop: "전투를 종료",
      combatStart: "전투를 시작",
    },
  },
  combat: {
    text: {
      miss: "빗나감!",
      critical: "치명타!",
    },
    info: {
      touchDoubleTapHint: "터치 환경에서는 한 번 터치하면 설명이 보이고, 같은 실행 버튼을 한 번 더 터치하면 동작합니다.",
    },
    log: {
      autoRestartAfterRecovery: "자동 전투 모듈이 지속 회복 후 전투를 재개합니다.",
    },
  },
  data: {
    displayNames: {
      STR: "근력",
      AGI: "민첩",
      VIT: "체력",
      INT: "지능",
      WIS: "정신",
      LUK: "행운",
      RES_PHYSICAL: "물리 저항",
      RES_FIRE: "화염 저항",
      RES_COLD: "냉기 저항",
      RES_LIGHTNING: "번개 저항",
      RES_WIND: "바람 저항",
      RES_EARTH: "대지 저항",
      RES_POISON: "독 저항",
      RES_LIGHT: "빛 저항",
      RES_DARK: "어둠 저항",
      RES_HOLY: "신성 저항",
      DIVINE: "신성",
      CHA: "매력",
      Weapon: "무기",
      Helmet: "투구",
      Armor: "갑옷",
      Gloves: "장갑",
      Boots: "신발",
      Necklace: "목걸이",
      Ring: "반지",
      Ring1: "반지 1",
      Ring2: "반지 2",
    },
    skills: {
      power_slash: {
        name: "강타",
        description: "무기를 강하게 휘둘러 적을 베어낸다.",
      },
      mana_bolt: {
        name: "마력탄",
        description: "압축한 마력을 적에게 쏘아 보낸다.",
      },
      quick_step: {
        name: "빠른 발놀림",
        description: "짧게 파고들어 적의 빈틈을 찌른다.",
      },
      guard_stance: {
        name: "방어 자세",
        description: "위험할 때 자세를 낮춰 호흡을 회복한다.",
      },
      mana_ignite: {
        name: "마력 점화",
        description: "흐릿한 마력을 순간적으로 점화해 적에게 터뜨린다.",
      },
      emergency_recovery: {
        name: "응급 회복",
        description: "체력이 낮을 때 자신을 회복한다.",
      },
    },
    equipmentNames: {
      rusty_sword: "녹슨 훈련검",
      hunter_bow: "견습 헌터의 활",
      golem_fist: "골렘 핵 철퇴",
      rift_blade: "균열 절단검",
      worn_gloves: "낡은 전투 장갑",
      wolf_leather_armor: "그림자 늑대 가죽갑옷",
      swift_boots: "숲길 추적자의 신발",
      sentinel_helmet: "파수병의 금 간 투구",
      tower_shield_armor: "탑 방벽 흉갑",
      mana_necklace: "잔류 마력 목걸이",
      ore_plate: "마석판 갑옷",
      lucky_ring: "광산의 행운 반지",
      shore_ring: "파도빛 반지",
      rift_gauntlets: "균열 각인 장갑",
      regressor_charm: "회귀자의 부적",
      warden_crown: "문지기의 균열 왕관",
      perfect_timeline_ring: "완벽한 세계선의 반지",
      ash_boots: "잿빛 발걸음",
      iron_gloves: "헌터 철제 장갑",
      novice_helmet: "초보자의 투구",
    },
    itemNames: {
      imp_codex_fragment: "균열 임프 카드 조각",
      low_mana_crystal_fragment: "하급 마정석 조각",
      quick_step_skill_fragment: "빠른 발놀림 스킬 조각",
    },
    itemDescriptions: {
      imp_codex_fragment: "균열 임프의 패턴을 도감에 기록하기 위한 정보 조각입니다.",
      low_mana_crystal_fragment: "장비 강화, 스킬룬, 도감 카드 합성의 기초 재료입니다.",
      quick_step_skill_fragment: "빠른 발놀림 스킬 해금과 숙련에 쓰이는 조각입니다.",
    },
    itemTypeLabels: {
      codex_fragment: "도감 카드 조각",
      mana_crystal: "마정석 조각",
      skill_fragment: "스킬 조각",
    },
    monsters: {
      shore_imp: "균열 임프",
      forest_wolf: "그늘 늑대",
      ruin_sentinel: "고장난 탑 파수병",
      mine_golem: "마석 광산 골렘",
      rift_knight: "균열 기사",
      rift_warden: "검은 관문의 파수꾼",
    },
    regions: {
      tutorial_shore: {
        name: "초심자의 해안",
        description: "첫 균열이 열린 해안. 약한 마물이 떠밀려온다.",
      },
      tutorial_forest: {
        name: "초심자의 숲",
        description: "그림자 늑대가 출몰하는 낮은 숲.",
      },
      broken_ruins: {
        name: "무너진 탑의 잔해",
        description: "탑의 파편과 고장난 파수병이 남은 폐허.",
      },
      mana_mine: {
        name: "마석 광산",
        description: "튜토리얼 섬의 성장을 가속하는 마석 광맥.",
      },
      rift_gate: {
        name: "검은 균열 관문",
        description: "섬의 마지막 관문. 제한시간 동안 파수꾼에게 누적 피해량을 증명한다.",
      },
    },
    gateMaps: {
      gate_tutorial_ruins_01: {
        name: "무너진 유적 게이트",
      },
    },
    shopCategories: {
      starter: {
        name: "초심자 보급",
        description: "튜토리얼 섬 초반 파밍을 부드럽게 만드는 기본 장비입니다.",
      },
      ruins: {
        name: "탑 잔해 전리품",
        description: "무너진 탑의 파편과 게이트 주변에서 회수한 장비입니다.",
      },
      regressor: {
        name: "회귀자 특수품",
        description: "반복 회차를 통해 가치를 알아보게 되는 고가의 장비입니다.",
      },
    },
    shopCatalogNotes: {
      shop_rusty_sword: "초반 공격력 보강용 지급검입니다.",
      shop_worn_gloves: "민첩을 조금 보태 전투 템포를 올립니다.",
      shop_novice_helmet: "초반 생존을 위한 보급형 투구입니다.",
      shop_wolf_leather_armor: "탑 잔해 구간의 첫 방어 목표입니다.",
      shop_swift_boots: "회피와 행동 속도 체감을 확인하기 좋은 장비입니다.",
      shop_mana_necklace: "마력탄 운용을 길게 가져가기 위한 목걸이입니다.",
      shop_lucky_ring: "드랍과 행운 체감 테스트에 적합한 반지입니다.",
      shop_regressor_charm: "회귀자 전용 성장감을 확인하기 위한 고가 장비입니다.",
    },
  },
  editorPrep: {
    locale: "ko-KR",
    loadFailed: "{url} 로드 실패 ({status})",
    summaryTitle: "에디터 준비 데이터 연결 완료",
    summaryCopy: "게임 본체를 우선 유지하면서, 나중에 에디터로 옮길 데이터 표면을 누락 없이 모으는 준비 화면입니다.",
    metrics: {
      panel: {
        label: "패널",
        value: "{count}개",
        hint: "미래 에디터 좌측 메뉴 기준",
      },
      imageSlot: {
        label: "이미지 슬롯",
        value: "{count}개",
        hint: "파일명/크롭 프리셋 준비",
      },
      audioSlot: {
        label: "사운드 슬롯",
        value: "{count}개",
        hint: "BGM/SFX 연결 준비",
      },
      backlog: {
        label: "대기 작업",
        value: "{count}개",
        hint: "추후 배치 업데이트 항목",
      },
        themeRetargetPreview: {
          label: "테마 미리보기",
          value: "텍스트 {textCount} · 에셋 {assetCount}",
          hint: "테마 전환 preview",
          readyHint: "무협 샘플 연결 준비 완료",
          reviewHint: "검토 필요 · 텍스트 {missingText} · 에셋 {missingAssets} · 불일치 {mismatchedAssets}",
        },
        balanceTuningRegistry: {
          label: "밸런스 표면",
          value: "그룹 {groupCount} · 파일 {fileCount}",
          hint: "밸런스 조정 표면 검토 필요",
          readyHint: "export {exportCount}개 검증 완료",
          reviewHint: "검토 필요 · export {exportCount}",
        },
        combatVfxPlacementPreview: {
          label: "?? VFX",
          value: "???? {playerRows} / ??? {monsterRows}",
          hint: "?? ?? ?? ????",
          readyHint: "?? ?? ?? ???? ?? ??",
          reviewHint: "?? ?? {effectTypes}? ?? ??",
        },
      },
    noPanel: "표시할 패널이 없습니다.",
    detailTitles: {
      dataTargets: "데이터 위치",
      assetSlots: "에셋 슬롯",
      editorFields: "편집 필드",
      futureControls: "미래 컨트롤",
      nodeTypes: "노드 타입",
    },
      retargetDetail: {
        title: "테마 전환 상세 미리보기",
      ready: "준비 완료",
      review: "검토 필요",
      route: "{source} → {target}",
      counts: "텍스트 {textCount} · 에셋 {assetCount} · 누락 {missingText}/{missingAssets} · 불일치 {mismatchedAssets}",
      textTitle: "텍스트 매핑 {count}개",
      assetTitle: "에셋 매핑 {count}개",
      sourcePath: "원본 경로",
      targetTextPath: "샘플 경로",
      sourceAsset: "원본 에셋",
      targetAsset: "샘플 에셋",
      assetSummary: "계획 파일 {plannedFile} · 매핑 {mappedTarget} · 슬롯 {slotCount}개",
      searchLabel: "검색",
      searchPlaceholder: "경로, 문구, 에셋 ID",
      typeFilter: "미리보기 종류 필터",
      all: "전체",
      textOnly: "텍스트",
      assetOnly: "에셋",
      visibleCount: "표시 {visible}/{total}",
      activeFilter: "필터 {filter}",
      activeSearch: "검색 \"{query}\"",
      activeFilterAndSearch: "필터 {filter} · 검색 \"{query}\"",
      textRow: "텍스트 행",
      assetRow: "에셋 행",
      expand: "펼침",
      collapse: "접기",
      reset: "초기화",
      empty: "표시할 항목 없음",
      emptyByType: "현재 {filter} 필터라 {section} 항목은 숨겨졌습니다.",
      emptyBySearch: "\"{query}\" 검색 결과가 없습니다.",
        emptyResetHint: "초기화를 누르면 전체 목록으로 돌아갑니다.",
      },
      balanceTuningDetail: {
        title: "밸런스 조정 표면",
        description: "수치 편집 전 확인하는 읽기 전용 레지스트리입니다.",
        summary: "그룹 {groupCount} · 파일 {fileCount} · export {exportCount}",
        exportCount: "export {count}",
        files: "파일",
        exports: "내보내기",
        affects: "영향 범위",
        relatedChecks: "자동 검사 연결",
        guards: "보호 범위",
        searchLabel: "검색",
        searchPlaceholder: "그룹, 파일, export, 영향 범위",
        scopeFilter: "범위 필터",
        allScopes: "전체",
        visibleCount: "표시 {visible}/{total}",
        reset: "초기화",
        activeFilter: "필터 {filter}",
        activeSearch: "검색 \"{query}\"",
        activeFilterAndSearch: "필터 {filter} · 검색 \"{query}\"",
        activeCandidate: "튜닝 후보 {candidate}",
        preview: "주요 수치 미리보기",
        previewArray: "{count}개 항목 · {sample}",
        previewObject: "{count}개 필드 · {sample}",
        previewValue: "값 {value}",
        previewMissing: "export 누락",
        pacingTitle: "튜토리얼 섬 페이싱",
        pacingDescription: "30분 MVP 목표 기준의 현재 레벨링 흐름입니다.",
        pacingStatusOk: "기준 통과",
        pacingStatusReview: "검토 필요",
        pacingKills: "목표 킬",
        pacingRequiredKillSeconds: "필요 평균",
        pacingPowerSlashMinutes: "강타 예상",
        pacingGold: "기본 골드",
        domainSummaries: "조절 영역 요약",
        domainImpact: "연결 규모",
        domainImpactSummary: "그룹 {groups} · 파일 {files} · export {exports}",
        domainPriority: "조절 우선순위",
        domainPriorityValue: "#{priority}",
        domainGroups: "연결 그룹",
        domainExports: "핵심 export",
        domainValueShapes: "값 형태",
        domainValueShapeItem: "{type} {count}개",
        domainValueRanges: "현재 값 범위",
        domainValueRangeNumber: "숫자 {min}~{max}",
        domainValueRangeObject: "객체 필드 {count}개",
        domainValueRangeArray: "배열 항목 {count}개",
        domainValueRangeEmpty: "범위 없음",
        domainChecks: "연결 검사",
        domainSignals: "주의 신호",
        valueTypeLabels: {
          array: "배열",
          boolean: "불리언",
          missing: "누락",
          null: "null",
          number: "숫자",
          object: "객체",
          string: "문자열",
          unknown: "알 수 없음"
        },
        domainWatch: "확인 포인트",
        domainLabels: {
          "player-foundation": "플레이어 성장 기반",
          "combat-pressure": "전투 압박감",
          "equipment-items": "장비와 아이템",
          "monster-reward-loop": "몬스터와 보상 루프",
          "theme-content-retarget": "테마 교체 콘텐츠"
        },
        domainDescriptions: {
          "player-foundation": "기본 스탯, 파생 스탯, 자유 포인트 흐름을 함께 본다.",
          "combat-pressure": "피해량, 스킬 비용, 하이퍼/브레이크, 회복 압박을 함께 본다.",
          "equipment-items": "상점 가격, 장비 점수, 아이템 스탯 예산과 전투력 체감을 함께 본다.",
          "monster-reward-loop": "몬스터 스탯, 경험치, 골드, 드랍과 오프라인 보상을 함께 본다.",
          "theme-content-retarget": "헌터물에서 무협 등 다른 테마로 바꿀 때 교체할 콘텐츠 경계를 본다."
        },
        domainSignalLabels: {
          "power-formula-drift": "전투력 산식 흔들림",
          "level-reward-too-fast": "레벨 보상 과속",
          "creation-stat-too-weak": "생성 스탯 약함",
          "kill-time-too-slow": "처치 시간 지연",
          "incoming-damage-too-high": "피해 압박 과함",
          "mp-recovery-pressure-off": "MP/회복 압박 어긋남",
          "shop-goal-unclear": "구매 목표 흐림",
          "recommended-gear-mismatch": "추천 장비 어긋남",
          "item-stat-budget-too-high": "아이템 예산 과함",
          "reward-pace-too-fast": "보상 속도 과속",
          "drop-target-unclear": "드랍 목표 흐림",
          "offline-reward-spike": "오프라인 보상 튐",
          "theme-swap-candidate-mixed": "테마 후보 섞임",
          "localization-asset-boundary-missing": "문구/에셋 경계 누락",
          "content-id-reuse-risk": "콘텐츠 ID 재사용 위험"
        },
        tuningCandidates: "튜닝 후보",
        candidatePriority: "조절 우선순위",
        candidatePriorityValue: "#{priority}",
        candidateSignals: "주의 신호",
        candidateImpact: "영향 요약",
        candidateImpactSummary: "그룹 {groups} · 파일 {files} · export {exports}",
        candidateValueRanges: "현재 값 범위",
        candidateGroups: "관련 그룹",
        candidateChecks: "연결 검사",
        empty: "표시할 밸런스 그룹 없음",
        emptyByFilter: "{filter} 범위에 표시할 밸런스 그룹이 없습니다.",
        emptyBySearch: "\"{query}\" 검색 결과가 없습니다.",
        emptyByFilterAndSearch: "{filter} 범위에서 \"{query}\" 검색 결과가 없습니다.",
        emptyByCandidate: "{candidate} 후보에 연결된 밸런스 그룹이 없습니다.",
        emptyResetHint: "초기화를 누르면 전체 밸런스 그룹으로 돌아갑니다.",
      },
      combatVfxPlacementDetail: {
        title: "?? VFX ?? ????",
        description: "????? ??? ?? ??? ???? ?? ?? ?? ?? ?? ???? ?????.",
        summary: "???? {playerRows} / ??? {monsterRows} / ?? {effectTypes}",
        playerTitle: "???? ?? ??",
        monsterTitle: "??? ?? ??",
        base: "??",
        hyper: "???",
        effects: "?? ??",
        motion: "??",
        sfx: "SFX",
        placement: "??",
        sprite: "?????",
        playerMetric: "???? VFX",
        monsterMetric: "??? VFX",
        effectMetric: "?? ??",
        classLabels: {
          warrior: "??",
          assassin: "???",
          fighter: "???",
          archer: "??",
          mage_wandbook: "??? ???",
          mage_staff: "??? ???",
        },
        genderLabels: {
          male: "??",
          female: "??",
        },
        effectLabels: {
          slash: "??",
          impact: "??",
          pierce: "??",
          projectile: "???",
          magic: "??",
          holy: "??",
          dark: "??",
          explosion: "??",
        },
      },
      assetTypes: {
        image: "이미지",
        audio: "사운드",
      slotTitle: "{title} 슬롯",
    },
    save: {
      saved: "저장됨",
      empty: "없음",
      count: "{count}개",
      noValue: "저장값 없음",
      chars: "{count}자",
      string: "문자열",
      array: "배열 {count}개",
      fields: "필드 {count}개",
      includesPlayer: "player 포함",
      includesSlots: "slots 포함",
    },
    status: {
      done: "완료",
      partial: "일부 준비",
      planned: "계획됨",
    },
    errorTitle: "에디터 데이터 로드 실패",
    unknownError: "알 수 없는 오류가 발생했습니다.",
  },
  gameLog: {
    newRegionUnlocked: "새 지역 개방: {regionName}.",
    completedGateReplay: "{regionName}의 확인된 게이트 경로를 재탐사합니다. 이전에 실제로 이동했던 노드 순서로만 반복 파밍할 수 있습니다.",
    restFinished: "휴식을 마치고 전투 대기 상태로 돌아왔습니다.",
    restStarted: "전투 지역에서 완전히 이탈해 휴식을 시작했습니다. HP와 MP 회복 속도가 증가합니다.",
    characterCreated: "시스템 등록이 완료되었습니다. 튜토리얼 섬으로 소환됩니다.",
  },
  statLog: {
    recommendedAllocated: "추천 배분 완료. {details}.",
    freeStatsReset: "확정 전 자유 스탯 배분을 초기화했습니다. {points}포인트를 회수했습니다.",
    freeStatsConfirmed: "자유 스탯 배분을 확정했습니다. {points}포인트는 이후 + / - 버튼으로 회수할 수 없습니다.",
  },
  regionMove: {
    notFound: "지역 정보를 찾을 수 없습니다.",
    blockedInCombat: "전투 중에는 지역을 이동할 수 없습니다.",
    gateIncomplete: "{regionName}의 게이트 끝 노드까지 도달해야 다음 지역으로 이동할 수 있습니다.",
  },
  developerLog: {
    optionChanged: "개발 테스트 옵션 변경: {label}.",
    regionSkippedToNext: "개발 테스트: {currentRegion} 완료 처리 후 {nextRegion} 지역으로 이동했습니다.",
    regionSkippedNoNext: "개발 테스트: {currentRegion} 지역을 완료 처리했습니다. 다음 지역은 아직 없습니다.",
  },
};
